/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-26 05:11:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.welfare.SABOK38;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class s00900_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.Box obox = null;
      obox = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("obox", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obox == null){
        obox = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("obox", obox, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
	RsWrapper codeWp = CodeUtil.getRsWrapper("PR_COMTB_CODE02_LIST","MULTCODE", "", "family_rel_cd|bank_cd@@@@A|","","","","","");
	boolean isEditable = false;
	if(obox.get("sign_status").equals("") || obox.get("sign_status").equals("1") || obox.get("sign_status").equals("4")) { isEditable = true; }

      out.write("\r\n");
      out.write("<!-- 양육비 신청서 작성 -->\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction goSave() {\r\n");
      out.write("\t\tif (formValidate(\"#main\")) {\r\n");
      out.write("\t\t\tif(document.main.apply_ymd.value.replace(/-/g,\"\") > '");
      out.print(DateUtil.toString("yyyyMMdd"));
      out.write("') { \r\n");
      out.write("\t\t\t\talert('신청일이  오늘 날짜 이후로 입력되었습니다.\\n다시 확인 후 입력해주세요.');\r\n");
      out.write("\t\t\t\tdocument.main.apply_ymd.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\tif(confirm('저장하시겠습니까?')) {\r\n");
      out.write("\t\t\t\tremoveMask(\"#main\");\r\n");
      out.write("\t\t\t\tdocument.main.action = 'wel01003_update.do';\r\n");
      out.write("\t\t\t\tdocument.main.target = '_self';\r\n");
      out.write("\t\t\t\tdocument.main.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\tfunction goCancel() {\r\n");
      out.write("\t\tremoveMask(\"#main\");\r\n");
      out.write("\t\tdocument.main.action = 'wel01002_select.do';\r\n");
      out.write("\t\tdocument.main.target = '_self';\r\n");
      out.write("\t\tdocument.main.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction find_employee_no_post(empl_no, empl_nm) {\r\n");
      out.write("\t\tremoveMask(\"#main\");\r\n");
      out.write("\t\tdocument.main.apply_no.value = '';\r\n");
      out.write("\t\tdocument.main.empl_no.value = empl_no;\r\n");
      out.write("\t\tdocument.main.empl_nm.value = empl_nm;\r\n");
      out.write("\t\tdocument.main.action = \"wel01003_edit.do\";\r\n");
      out.write("\t\tdocument.main.target = \"_self\";\r\n");
      out.write("\t\tdocument.main.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction __Calendar_Setting_Post(target) {\r\n");
      out.write("\t\tif(target.substring(0,9) == 'start_ymd') {\r\n");
      out.write("\t\t\tinx = target.substring(9);\r\n");
      out.write("\t\t\tif(!isEmpty(document.all['end_ymd'+inx])) {\r\n");
      out.write("\t\t\t\tdocument.all['inner_ilsu'+inx].value = getDayInterval(document.all['start_ymd'+inx].value.replace(/-/g,\"\")+'000', document.all['end_ymd'+inx].value.replace(/-/g,\"\")+'000') + 1;\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t\t}else if(target.substring(0,7) == 'end_ymd') {\r\n");
      out.write("\t\t\tinx = target.substring(7);\t\t\r\n");
      out.write("\t\t\tif(!isEmpty(document.all['start_ymd'+inx])) {\r\n");
      out.write("\t\t\t\tdocument.all['inner_ilsu'+inx].value = getDayInterval(document.all['start_ymd'+inx].value.replace(/-/g,\"\")+'000', document.all['end_ymd'+inx].value.replace(/-/g,\"\")+'000') + 1;\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t_f_format(document.all['inner_ilsu'+inx]);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form id=\"main\" name=\"main\" method=\"post\" action=\"\" class=\"fType\" style=\"margin:0px\">\r\n");
      out.write("<input type=\"hidden\" name=\"bugt_cd\" \tvalue=\"");
      out.print(box.get("bugt_cd"));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"apply_no\" \tvalue=\"");
      out.print(box.get("apply_no"));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t<table class=\"table table-view table-bordered table-cover marB5\">\r\n");
      out.write("\t");
 if(uSesEnt.use_auth.startsWith("S")) { 
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>사원선택</th>\r\n");
      out.write("\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group input-medium\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"empl_nm\" value=\"");
      out.print(obox.get("empl_nm",Box.SPECIAL_CHAR));
      out.write("\" class=\"form-control\" style=\"width:90px\" readOnly>\r\n");
      out.write("\t\t\t\t\t<span class=\"input-group-btn\"><button type=\"button\" class=\"btn dark\" onClick=\"findEmployeeNo('')\"><i class=\"fa fa-search\"></i></button></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th width=\"15%\">사번/성명</th>\r\n");
      out.write("\t\t\t<td width=\"35%\">");
      out.print(obox.get("empl_no"));
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"javascript:goEmployeePop('");
      out.print(obox.get("empl_no"));
      out.write("')\">");
      out.print(obox.get("empl_nm"));
      out.write("</a>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"empl_no\" value=\"");
      out.print(obox.get("empl_no"));
      out.write("\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<th width=\"15%\">부서</th>\r\n");
      out.write("\t\t\t<td width=\"35%\">");
      out.print(obox.get("dept_nm"));
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>주민번호</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(FormatUtil.juminNo(obox.get("reside_no"),"x"));
      out.write("</td>\r\n");
      out.write("\t\t\t<th>직위</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(obox.get("position_nm"));
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>입사일자</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(obox.get("entry_ymd",Box.DEF_DATE_FMT));
      out.write("</td>\r\n");
      out.write("\t\t\t<th>사원구분</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(obox.get("empl_class_nm"));
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table class=\"table table-view table-bordered table-cover marB5\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>자녀구분</th>\r\n");
      out.write("\t\t\t<td width=\"35%\">\r\n");
      out.write("\t\t\t\t<select name=\"data12\" class=\"bs-select form-control required\" style=\"width:40%\">\r\n");
      out.write("\t\t\t\t\t<option value=''>:: 선택 ::</option>\r\n");
      out.write("\t\t\t\t\t<option value='첫째' ");
      out.print(box.get("data12").equals("첫째")?"selected":"");
      out.write(">첫째</option>\r\n");
      out.write("\t\t\t\t\t<option value='둘째' ");
      out.print(box.get("data12").equals("둘째")?"selected":"");
      out.write(">둘째</option>\r\n");
      out.write("\t\t\t\t\t<option value='셋째' ");
      out.print(box.get("data12").equals("셋째")?"selected":"");
      out.write(">셋째</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<th width=\"15%\">자녀나이</th>\r\n");
      out.write("\t\t\t<td width=\"35%\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"data13\" value=\"");
      out.print(obox.get("data13"));
      out.write("\" size=\"10\" maxlength=\"15\" title=\"자녀나이\"  class=\"form-control required\" style=\"width:45px\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th width=\"15%\">신청일자</th>\r\n");
      out.write("\t\t\t<td width=\"35%\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group input-medium date date-picker\" data-date=\"\" data-date-format=\"yyyy-mm-dd\" data-date-viewmode=\"years\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"apply_ymd\" value=\"");
      out.print(box.get("apply_no").equals("") ? DateUtil.toString("yyyyMMdd") : obox.get("apply_ymd"));
      out.write("\" maxlength=\"8\" title=\"신청일자\" class=\"form-control required tYMD\" ");
      out.print(isEditable?"":"readonly");
      out.write(">\r\n");
      out.write("\t\t\t\t\t<span class=\"input-group-btn\"><button class=\"btn dark\" type=\"button\"><i class=\"fa fa-calendar\"></i></button></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<th width=\"15%\">신청금액</th>\r\n");
      out.write("\t\t\t<td width=\"35%\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"apply_amt\" value=\"");
      out.print(obox.get("apply_amt").equals("")?"3000000":obox.get("apply_amt"));
      out.write("\" maxlength=\"10\" title=\"신청금액\" class=\"form-control required tMONEY\" style=\"width:100px\"> 원\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>계좌번호</th>\r\n");
      out.write("\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t<select name=\"bank_cd\" title=\"금융기관\" ");
if(!uSesEnt.corp_cd.equals("SABOK27")){
      out.write("class=\"bs-select form-control required\"");
}
      out.write(" style=\"width:120px\">\r\n");
      out.write("\t\t\t\t\t<option value=''>:: 금융기관 선택 ::</option>\r\n");
      out.write("\t\t            ");
      out.print(CodeUtil.optList(codeWp, "bank_cd", obox.get("bank_cd")));
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"account_no\" value=\"");
      out.print(obox.get("account_no"));
      out.write("\" size=\"18\" maxlength=\"30\" title=\"계좌번호\" ");
if(!uSesEnt.corp_cd.equals("SABOK27")){
      out.write("class=\"form-control required\"");
}
      out.write(" style=\"width:100px\">&nbsp;예금주 :\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"account_owner\" value=\"");
      out.print(obox.get("account_owner"));
      out.write("\" size=\"10\" maxlength=\"15\" title=\"예금주\" ");
if(!uSesEnt.corp_cd.equals("SABOK27")){
      out.write("class=\"form-control required\"");
}
      out.write(" style=\"width:100px\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>비고</th>\r\n");
      out.write("\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"etc_remark\" value=\"");
      out.print(obox.get("etc_remark"));
      out.write("\" maxlength=\"120\" title=\"비고\"  class=\"form-control\" style=\"width:90%\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");
 if(!box.get("apply_no").equals("")) { 
      out.write("\r\n");
      out.write("  \t\t<tr>\r\n");
      out.write("\t\t\t<th>전표번호</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t");
if(!obox.get("slip_no").equals("")){
      out.write("&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:goSlipViewer('&slip_no=");
      out.print(obox.get("slip_no"));
      out.write("');\">");
      out.print(obox.get("slip_no",Box.SLIP_NO));
      out.write("</a>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"slip_no\" \tvalue=\"");
      out.print(obox.get("slip_no"));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"sign_status\" value=\"");
      out.print(obox.get("sign_status"));
      out.write("\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<th>결재상태</th>\r\n");
      out.write("\t\t\t<td><b><font color=red>");
      out.print(obox.get("sign_status_nm"));
      out.write("</font></b></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"table-bottom-control\">\r\n");
      out.write("\t\t<span class=\"f-right\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn dark\" onClick=\"goSave()\"><img src=\"/com/img/ico_btn_save.png\">저장</button>\r\n");
      out.write("\t\t");
if(!box.get("apply_no").equals("")){
      out.write("\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn dark\" onClick=\"goCancel()\"><img src=\"/com/img/ico_btn_refresh_edit.png\">취소</button>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
