/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-17 10:57:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class inf01003_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/com/daumeditor/incDaumEditor.jsp", Long.valueOf(1565704428000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.Box obox = null;
      obox = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("obox", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obox == null){
        obox = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("obox", obox, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.RsWrapper fileWp = null;
      fileWp = (egovframework.cbiz.RsWrapper) _jspx_page_context.getAttribute("fileWp", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (fileWp == null){
        fileWp = new egovframework.cbiz.RsWrapper();
        _jspx_page_context.setAttribute("fileWp", fileWp, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<!-- 공지사항  등록/수정 -->\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tvar fileCnt = ");
      out.print(fileWp.getLength());
      out.write(";\r\n");
      out.write("\tfunction goSave() {\r\n");
      out.write("\t\tif (formValidate(\"#main\")) {\r\n");
      out.write("\t\t\tEditor.save();\r\n");
      out.write("\t\t\tif(document.main.due_ymd.value.replace(/-/g,\"\") < '");
      out.print(DateUtil.toString("yyyyMMdd"));
      out.write("') {\r\n");
      out.write("\t\t\t\talert('공지기한은 오늘 날짜 이후이어야 합니다.');\r\n");
      out.write("\t\t\t\tdocument.main.due_ymd.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(confirm('저장하시겠습니까?')) {\t\t\t\t\r\n");
      out.write("\t\t\t\tdocument.main.input_cnt.value = fileCnt;\r\n");
      out.write("\t\t\t\tajaxSubmitForm(\"inf01003_update.do\",\"#main\", function(rtn) {\r\n");
      out.write("\t\t\t\t\tif(rtn.isOk == \"Y\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"저장되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\tgoCancel();\r\n");
      out.write("\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\talert(rtn.errMsg);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction goAddFile() {\r\n");
      out.write("\t\tvar cHtml = \"<tr id='attachDocRow\"+fileCnt+\"'>\"\r\n");
      out.write("\t\t\t\t  + \"\t<td>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t<div class='form-inline'>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t<div class='form-group'>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t<div class='fileinput fileinput-new input-group' data-provides='fileinput'>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t\t<div class='bs-select form-control input-fixed' data-trigger='fileinput' style='width:400px;'>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t\t\t<i class='fa fa-file fileinput-exists'></i>&nbsp;<span class='fileinput-filename'></span>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t\t</div>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t\t<span class='input-group-addon btn dark btn-file'>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t\t\t<span class='fileinput-new'>파일찾기</span><span class='fileinput-exists'>파일교체</span>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t\t\t<input type='file' id='attach_doc\"+fileCnt+\"' name='attach_doc\"+fileCnt+\"'>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t\t</span>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t\t</div>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t</div>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t<button type='button' class='btn btn-primary btn-table marL10 marR0' onClick=\\\"goAddFile()\\\">추가</button>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t\t<button type='button' class='btn btn-primary btn-table marR0' onClick=\\\"goDelFile('attachDocRow\"+fileCnt+\"')\\\">삭제</button>\"\r\n");
      out.write("\t\t\t\t  + \"\t\t</div>\"\r\n");
      out.write("\t\t\t\t  + \"\t</td>\"\r\n");
      out.write("\t\t\t\t  + \"</tr>\";\r\n");
      out.write("\t\t$(\"#attachDocTable\").append(cHtml);\r\n");
      out.write("\t\tappendHtmlAfterWork(\"#attachDocRow\"+fileCnt);\r\n");
      out.write("\t\tfileCnt++;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goDelFile(id) {\r\n");
      out.write("\t\tif($(\"input:file[name^='attach_doc']\").length > 1) {\r\n");
      out.write("\t\t\t$(\"#\"+id).remove();\r\n");
      out.write("\t\t}else { \r\n");
      out.write("\t\t\talert('더 이상 삭제할 수 없습니다.');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goDeleteFile(file_no, file_path) {\r\n");
      out.write("\t\tif(confirm('첨부파일을 삭제하시겠습니까?')) {\r\n");
      out.write("\t\t\tdocument.main.file_no.value = file_no;\r\n");
      out.write("\t\t\tdocument.main.file_path.value = file_path;\r\n");
      out.write("\t\t\tajaxSubmitForm(\"inf01003_delete_file.do\",\"#main\", function(rtn) {\r\n");
      out.write("\t\t\t\tif(rtn.isOk == \"Y\") {\r\n");
      out.write("\t\t\t\t\treturnFormSubmit(document.main, 'inf01003_edit.do');\r\n");
      out.write("\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\talert(rtn.errMsg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goCancel() {\r\n");
      out.write("\t\tdocument.main.action = 'inf01001_list.do';\r\n");
      out.write("\t\tdocument.main.target = '_self';\r\n");
      out.write("\t\tdocument.main.submit();\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tgoAddFile();\r\n");
      out.write("\t});\t\r\n");
      out.write("</script>\r\n");
      out.write("<form id=\"main\" name=\"main\" method=\"post\" action=\"\" class=\"fType\" enctype=\"multipart/form-data\">\r\n");
      out.write("<input type=\"hidden\" name=\"inform_no\" \tvalue=\"");
      out.print(obox.get("inform_no"));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"pathKey\"\t\tvalue=\"community\">\r\n");
      out.write("<input type=\"hidden\" name=\"file_no\"\t\tvalue=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"file_nm\"\t\tvalue=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"file_path\"\tvalue=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"input_cnt\" \tvalue=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 class=\"page-title\">공지사항</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"scrollOptionY\" style=\"height:calc(100vh - 60px)\">\r\n");
      out.write("\t\t<table class=\"table table-view table-bordered table-cover mar0\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col style=\"width:15%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:35%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:15%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:35%;\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" name=\"inform_head\" value=\"");
      out.print(obox.get("inform_head"));
      out.write("\" title=\"제목\" class=\"bs-select form-control required\" style=\";width:500px;\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"inform_body\" id=\"inform_body\" style=\"display:none\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t");
	request.setAttribute("initContents", obox.get("inform_body").replace("<photo","<img"));
							request.setAttribute("contents_fld_nm", "inform_body");
							request.setAttribute("form_name", "main");
							request.setAttribute("editor_height", "470"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.write('\n');
      out.write('\n');
	String initContents = ((String)request.getAttribute("initContents")).replaceAll("&nbsp;","&amp;nbsp");
	String contentsFldNm = (String)request.getAttribute("contents_fld_nm");
	String formName = (String)request.getAttribute("form_name");
	String editorWidth = (String)request.getAttribute("editor_width");
	String contentWidth = "";
	if (request.getAttribute("content_width") != null) {
		contentWidth = (String)request.getAttribute("content_width");
	}
	String editorHeight = (String)request.getAttribute("editor_height");
	String editorPadding = (String)request.getAttribute("editor_padding");
	String toolbarBasic = FormatUtil.nvl2((String)request.getAttribute("toolbar_basic"),""); 
	String toolbarAdvanced = FormatUtil.nvl2((String)request.getAttribute("toolbar_advanced"),""); 
	
	String myPage = request.getRequestURL().toString();
	String svr_domain = myPage.substring(0, myPage.indexOf("/WEB-INF/"));
	
	String readonly = (String)request.getAttribute("readonly");
	String display = (String)request.getAttribute("display");

      out.write("\n");
      out.write("\n");
      out.write("<!-- HTML 편집기 시작 -->\n");
      out.write("<div class=\"body\">\n");
      out.write("\t<div id=\"tx_trex_container\" class=\"tx-editor-container\" style=\"width:");
      out.print(editorWidth);
      out.write("px;\">\n");
      out.write("\t\t<div id=\"tx_toolbar_basic\" class=\"tx-toolbar tx-toolbar-basic\" style=\"display:");
      out.print(toolbarBasic);
      out.write("\">\n");
      out.write("\t\t\t<div class=\"tx-toolbar-boundary\">\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontfamily\" unselectable=\"on\" class=\"tx-slt-70bg tx-fontfamily\"><a href=\"javascript:;\" title=\"글꼴\">굴림</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontfamily_menu\" class=\"tx-fontfamily-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-42bg tx-fontsize\" id=\"tx_fontsize\"><a href=\"javascript:;\" title=\"글자크기\">11pt</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontsize_menu\" class=\"tx-fontsize-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-font\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-lbg tx-bold\" id=\"tx_bold\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"굵게 (Ctrl+B)\">굵게</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-bg tx-underline\" id=\"tx_underline\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"밑줄 (Ctrl+U)\">밑줄</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-bg tx-italic\" id=\"tx_italic\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"기울임 (Ctrl+I)\">기울임</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-bg tx-strike\" id=\"tx_strike\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"취소선 (Ctrl+D)\">취소선</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-tbg tx-forecolor\" id=\"tx_forecolor\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"글자색\">글자색</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"글자색 선택\">글자색 선택</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_forecolor_menu\" class=\"tx-menu tx-forecolor-menu tx-colorpallete\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-brbg tx-backcolor\" id=\"tx_backcolor\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"글자 배경색\">글자 배경색</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"글자 배경색 선택\">글자 배경색 선택</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_backcolor_menu\" class=\"tx-menu tx-backcolor-menu tx-colorpallete\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-lbg tx-alignleft\" id=\"tx_alignleft\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"왼쪽정렬 (Ctrl+,)\">왼쪽정렬</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-bg tx-aligncenter\" id=\"tx_aligncenter\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"가운데정렬 (Ctrl+.)\">가운데정렬</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-bg tx-alignright\" id=\"tx_alignright\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"오른쪽정렬 (Ctrl+/)\">오른쪽정렬</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-rbg tx-alignfull\" id=\"tx_alignfull\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"양쪽정렬\">양쪽정렬</a></div></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-tab\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-lbg tx-indent\" id=\"tx_indent\"><a href=\"javascript:;\" title=\"들여쓰기 (Tab)\" class=\"tx-icon\">들여쓰기</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-rbg tx-outdent\" id=\"tx_outdent\"><a href=\"javascript:;\" title=\"내어쓰기 (Shift+Tab)\" class=\"tx-icon\">내어쓰기</a></div></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-list\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-31lbg tx-lineheight\" id=\"tx_lineheight\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"줄간격\">줄간격</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"줄간격\">줄간격 선택</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_lineheight_menu\" class=\"tx-lineheight-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-etc\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-bg tx-specialchar\" id=\"tx_specialchar\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"특수문자\">특수문자</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_specialchar_menu\" class=\"tx-specialchar-menu tx-menu\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-bg tx-table\" id=\"tx_table\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"표만들기\">표만들기</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_table_menu\" class=\"tx-table-menu tx-menu\" unselectable=\"on\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-inner\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-preview\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-rowcol\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-deco\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-enter\"></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-rbg tx-horizontalrule\" id=\"tx_horizontalrule\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"구분선\">구분선</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_horizontalrule_menu\" class=\"tx-horizontalrule-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-undo\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-lbg tx-undo\" id=\"tx_undo\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"실행취소 (Ctrl+Z)\">실행취소</a></div></li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-rbg tx-redo\" id=\"tx_redo\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"다시실행 (Ctrl+Y)\">다시실행</a></div></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-image\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" id=\"tx_image\" class=\"tx-image tx-btn-trans\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"사진\" class=\"tx-text\">사진</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t");
 if(!toolbarAdvanced.equals("none")) { 
      out.write("\t\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-right\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-btn-nlrbg tx-advanced\" id=\"tx_advanced\"><a href=\"javascript:;\" class=\"tx-icon\" title=\"툴바 더보기\">툴바 더보기</a></div></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-right tx-nav-opt\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div unselectable=\"on\" class=\"tx-switchtoggle\" id=\"tx_switchertoggle\"><a href=\"javascript:;\" title=\"에디터 타입\">에디터</a></div></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t");
 } 
      out.write("\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
 if(!toolbarAdvanced.equals("none")) { 
      out.write("\n");
      out.write("\t\t<div id=\"tx_toolbar_advanced\" class=\"tx-toolbar tx-toolbar-advanced\">\n");
      out.write("\t\t\t<div class=\"tx-toolbar-boundary\">\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\"><div class=\"tx-tableedit-title\"></div></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-lbg tx-mergecells\" id=\"tx_mergecells\"><a href=\"javascript:;\" class=\"tx-icon2\" title=\"병합\">병합</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_mergecells_menu\" class=\"tx-mergecells-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-bg tx-insertcells\" id=\"tx_insertcells\"><a href=\"javascript:;\" class=\"tx-icon2\" title=\"삽입\">삽입</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_insertcells_menu\" class=\"tx-insertcells-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-rbg tx-deletecells\" id=\"tx_deletecells\"><a href=\"javascript:;\" class=\"tx-icon2\" title=\"삭제\">삭제</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_deletecells_menu\" class=\"tx-deletecells-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinepreview\" unselectable=\"on\" class=\"tx-slt-70lbg tx-cellslinepreview\"><a href=\"javascript:;\" title=\"선 미리보기\"></a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinepreview_menu\" class=\"tx-cellslinepreview-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinecolor\" unselectable=\"on\" class=\"tx-slt-tbg tx-cellslinecolor\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"선색\">선색</a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-colorpallete\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinecolor_menu\" class=\"tx-cellslinecolor-menu tx-menu tx-colorpallete\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslineheight\" unselectable=\"on\" class=\"tx-btn-bg tx-cellslineheight\"><a href=\"javascript:;\" class=\"tx-icon2\" title=\"두께\">두께</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslineheight_menu\" class=\"tx-cellslineheight-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinestyle\" unselectable=\"on\" class=\"tx-btn-bg tx-cellslinestyle\"><a href=\"javascript:;\" class=\"tx-icon2\" title=\"스타일\">스타일</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinestyle_menu\" class=\"tx-cellslinestyle-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellsoutline\" unselectable=\"on\" class=\"tx-btn-rbg tx-cellsoutline\"><a href=\"javascript:;\" class=\"tx-icon2\" title=\"테두리\">테두리</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellsoutline_menu\" class=\"tx-cellsoutline-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tablebackcolor\" unselectable=\"on\" class=\"tx-btn-lrbg tx-tablebackcolor\" style=\"background-color:#9aa5ea;\"><a href=\"javascript:;\" class=\"tx-icon2\" title=\"테이블 배경색\">테이블 배경색</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tablebackcolor_menu\" class=\"tx-tablebackcolor-menu tx-menu tx-colorpallete\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tabletemplate\" unselectable=\"on\" class=\"tx-btn-lrbg tx-tabletemplate\"><a href=\"javascript:;\" class=\"tx-icon2\" title=\"테이블 서식\">테이블 서식</a></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tabletemplate_menu\" class=\"tx-tabletemplate-menu tx-menu tx-colorpallete\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t\t<div id=\"tx_canvas\" class=\"tx-canvas\">\n");
      out.write("\t\t\t<div id=\"tx_loading\" class=\"tx-loading\">\n");
      out.write("\t\t\t\t<div><img src=\"/com/plugins/daumeditor/images/icon/editor/loading2.png\" width=\"113\" height=\"21\" align=\"absmiddle\"/></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"tx_canvas_wysiwyg_holder\" class=\"tx-holder\" style=\"display:block;\"><iframe id=\"tx_canvas_wysiwyg\" name=\"tx_canvas_wysiwyg\" allowtransparency=\"true\" frameborder=\"0\"></iframe></div>\n");
      out.write("\t\t\t<div class=\"tx-source-deco\">\n");
      out.write("\t\t\t\t<div id=\"tx_canvas_source_holder\" class=\"tx-holder\"><textarea id=\"tx_canvas_source\" rows=\"30\" cols=\"30\"></textarea></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"tx_canvas_text_holder\" class=\"tx-holder\"><textarea id=\"tx_canvas_text\" rows=\"30\" cols=\"30\"></textarea></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"tx_attach_div\" class=\"tx-attach-div\" style='display:none'>\n");
      out.write("\t\t\t<div id=\"tx_attach_txt\" class=\"tx-attach-txt\" style='display:none'>파일 첨부</div>\n");
      out.write("\t\t\t<div id=\"tx_attach_box\" class=\"tx-attach-box\" style='display:none'>\n");
      out.write("\t\t\t\t<div class=\"tx-attach-box-inner\">\n");
      out.write("\t\t\t\t\t<div id=\"tx_attach_preview\" class=\"tx-attach-preview\"><p></p><img src=\"/com/plugins/daumeditor/images/icon/editor/pn_preview.gif\" width=\"147\" height=\"108\" unselectable=\"on\"/></div>\n");
      out.write("\t\t\t\t\t<div class=\"tx-attach-main\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_upload_progress\" class=\"tx-upload-progress\">\n");
      out.write("\t\t\t\t\t\t\t<div>0%</div>\n");
      out.write("\t\t\t\t\t\t\t<p>파일을 업로드하는 중입니다.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<ul class=\"tx-attach-top\">\n");
      out.write("\t\t\t\t\t\t\t<li id=\"tx_attach_delete\" class=\"tx-attach-delete\"><a>전체삭제</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"tx_attach_size\" class=\"tx-attach-size\">파일: <span id=\"tx_attach_up_size\" class=\"tx-attach-size-up\"></span>/<span id=\"tx_attach_max_size\"></span></li>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"tx_attach_tools\" class=\"tx-attach-tools\"></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t<ul id=\"tx_attach_list\" class=\"tx-attach-list\"></ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<textarea id=\"init_contents_textarea\" style=\"display:none;\">");
      out.print(initContents);
      out.write("</textarea>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar config = {\n");
      out.write("\t\ttxHost: '");
      out.print(svr_domain);
      out.write("', txPath: '', txService: 'sample', txProject: 'sample', initializedId: \"\", wrapper: \"tx_trex_container\",\n");
      out.write("\t\tform: '");
      out.print(formName);
      out.write("'+\"\",\n");
      out.write("\t\ttxIconPath: \"/com/plugins/daumeditor/images/icon/editor/\",\n");
      out.write("\t\ttxDecoPath: \"/com/plugins/daumeditor/images/deco/contents/\",\n");
      out.write("\t\tcanvas: {\n");
      out.write("\t\t\treadonly:");
      out.print(readonly);
      out.write(",\n");
      out.write("            exitEditor:{},\n");
      out.write("\t\t\tstyles: {color: \"#000000\", fontFamily: \"바탕체\", fontSize: \"10pt\", backgroundColor: \"#fff\", lineHeight: \"1.5\", padding: \"");
      out.print(FormatUtil.nvl2(editorPadding,"10"));
      out.write("px\"},\n");
      out.write("\t\t\tshowGuideArea: false\n");
      out.write("\t\t},\n");
      out.write("\t\tevents: { preventUnload: false },\n");
      out.write("\t\tsidebar: {\n");
      out.write("\t\t\tattachbox: { show: true, confirmForDeleteAll: true }\n");
      out.write("\t\t},\n");
      out.write("\t\t");
 if (contentWidth.equals("") == false) { 
      out.write("\n");
      out.write("\t\tsize: { contentWidth: ");
      out.print(editorWidth);
      out.write(" }\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t};\n");
      out.write("\tEditorJSLoader.ready(function(Editor) {\n");
      out.write("\t\tvar editor = new Editor(config);\n");
      out.write("\t\tEditor.getCanvas().setCanvasSize({height:\"");
      out.print(editorHeight);
      out.write("px\"});\n");
      out.write("\t\tdocument.getElementById(\"tx_toolbar_basic\").style.display = '");
      out.print(display);
      out.write("';\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tfunction saveContent() { Editor.save(); }\n");
      out.write("\tfunction validForm(editor) {\n");
      out.write("\t\tvar validator = new Trex.Validator();\n");
      out.write("\t\tvar content = editor.getContent();\n");
      out.write("\t\tif(!validator.exists(content)) { return false; }\n");
      out.write("\t\treturn true;\n");
      out.write("\t}\n");
      out.write("\tfunction setForm(editor) {\n");
      out.write("        var i, input;\n");
      out.write("        var form = editor.getForm();\n");
      out.write("        var content = editor.getContent();\n");
      out.write("        document.");
      out.print(formName);
      out.write('.');
      out.print(contentsFldNm);
      out.write(".value = content;\n");
      out.write("        if(content != null) { return; }\n");
      out.write("\t}\n");
      out.write("\tfunction loadContent() {\n");
      out.write("\t\tEditor.modify({\n");
      out.write("\t\t\t\"content\": document.getElementById(\"init_contents_textarea\")\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\tsetTimeout(\"loadContent();\",500);\n");
      out.write("</script>\n");
      out.write("<!-- HTML 편집기 끝 -->");
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>첨부파일</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t");
 for(int i=0; i < fileWp.getLength(); i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:fileDownload(document.main,'");
      out.print(fileWp.get("file_path",i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileWp.get("file_nm",i));
      out.write("')\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/com/img/ico_disk.png\"> ");
      out.print(fileWp.get("file_nm",i));
      out.write(' ');
      out.write('(');
      out.print(fileWp.get("file_size",i,Box.THOUSAND_COMMA));
      out.write(" Byte)</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:goDeleteFile('");
      out.print(fileWp.get("file_no",i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(fileWp.get("file_path",i));
      out.write("');\"><img src=\"/com/img/ico_btn_delete.png\"></a><br>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<table id=\"attachDocTable\">\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(box.get("inform_no").equals("")? uSesEnt.empl_nm : obox.get("sys_reg_nm"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(box.get("inform_no").equals("")? DateUtil.defFmtDateTimeAPM(DateUtil.toString("yyyyMMddHHmmss")) : obox.get("sys_upd_date",Box.DEF_DATETIME_FMT_APM));
      out.write("</td>\t\t\t \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t<th>공지기한</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group input-medium date date-picker\" data-date=\"");
      out.print(obox.get("due_ymd",Box.DEF_DATE_FMT));
      out.write("\" data-date-format=\"yyyy-mm-dd\" data-date-viewmode=\"years\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"due_ymd\" name=\"due_ymd\" value=\"");
      out.print(obox.get("due_ymd"));
      out.write("\" maxlength=\"8\" title=\"공지기한\" class=\"bs-select form-control tYMD\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-btn\"><button class=\"btn dark\" type=\"button\"><i class=\"fa fa-calendar\"></i></button></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t \r\n");
      out.write("\t\t\t\t\t<th>자동알림</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<label class=\"mt-checkbox mt-checkbox-outline\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"popup_yn\" value=\"Y\" ");
      out.print(obox.get("popup_yn").equals("Y") ? "checked" :"");
      out.write(">로그인 시 팝업<span/>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 if(uSesEnt.use_auth.equals("SA")) { 
      out.write("\t\r\n");
      out.write("\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t<th>공지대상</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"corp_cd\" title=\"공지대상\" class=\"bs-select form-control\" style=\"width:200px\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=''>전체</option>\r\n");
      out.write("\t                \t\t");
      out.print(CodeUtil.optList("PR_COMTB_CORP01_LIST","LISTCODE",obox.get("corp_cd"),"","","","",""));
      out.write("\r\n");
      out.write("\t                \t</select> \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 }else { 
      out.write("\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"corp_cd\" value=\"");
      out.print(uSesEnt.dbo);
      out.write("\">\r\n");
      out.write("\t\t\t");
 } 
      out.write("\t\r\n");
      out.write("\t\t\t</tbody>\t\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"table-bottom-control\">\r\n");
      out.write("\t\t\t<span style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t<span style=\"float:right;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn dark\" onclick=\"goSave();\"><img src=\"/com/img/ico_btn_save.png\">저장</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn dark\" onclick=\"goCancel();\"><img src=\"/com/img/ico_btn_cancel.png\">취소</button>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
