/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-27 05:29:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class acc02001_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/com/include/excel_header.jsp", Long.valueOf(1568793281369L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.RsWrapper rsWp = null;
      rsWp = (egovframework.cbiz.RsWrapper) _jspx_page_context.getAttribute("rsWp", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (rsWp == null){
        rsWp = new egovframework.cbiz.RsWrapper();
        _jspx_page_context.setAttribute("rsWp", rsWp, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
 if(box.get("excel_yn").equals("Y")) { box.put("ajax_yn", "Y"); 
      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
	
	String lm_sAgentType = request.getHeader("User-Agent"); 
	String excel_file_nm = box.get("excel_file_nm");
	excel_file_nm = StringUtil.get8859_1(excel_file_nm); // ìë²ììë ì£¼ìì²ë¦¬
	response.reset();
    if(lm_sAgentType.indexOf("MSIE 5.5") > -1 || lm_sAgentType.indexOf("MSIE 6.0") > -1) {
	    response.setHeader("Content-Type",        "doesn/matter;");
	    response.setHeader("Content-Disposition", "filename="+excel_file_nm+".xls");
    }else {
	    response.setHeader("Content-Type", "application/vnd.ms-excel;charset=UTF-8");
    	response.setHeader("Content-Disposition", "attachment;filename="+excel_file_nm+".xls");
	}
	response.setHeader("Content-Transfer-Encoding", "binary;");
	response.setHeader("Pragma", "no-cache;");
	response.setHeader("Expires", "-1;");

      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\ttd { font-size:12px; font-family:\"ë§ì ê³ ë\", \"Arial\", \"sans-serif\"; color:#00000; text-align:center; border:.5pt solid #000; }\n");
      out.write("</style>\n");
      out.write("<center><h2>");
      out.print(box.get("excel_file_nm"));
      out.write("</h2></center>");
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("<!-- 거래처코드  -->\r\n");
 if(!box.get("ajax_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction goSearch(cust_cd) {\r\n");
      out.write("\t\tdocument.main.page_count.value = '';\r\n");
      out.write("\t\tajaxReplaceForm(\"acc02001_list.do\", \"#main\", \"#divListData\", function() {\r\n");
      out.write("\t\t\tif(cust_cd == '') {\r\n");
      out.write("\t\t\t\tif ($(\"tr[id='tr_0']\").attr(\"cust_cd\") != undefined) {\r\n");
      out.write("\t\t\t\t\tgoEdit($(\"tr[id='tr_0']\").attr(\"cust_cd\"));\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\tgoEdit(cust_cd); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfixTableHeader(\"MyTable\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction goExcel() {\r\n");
      out.write("\t\tdocument.main.action = \"acc02001_list.do?excel_yn=Y\";\r\n");
      out.write("\t\tdocument.main.target = \"_self\";\r\n");
      out.write("\t\tdocument.main.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goPage(page_count) {\r\n");
      out.write("\t\tdocument.main.page_count.value = page_count;\r\n");
      out.write("\t\tajaxReplaceForm(\"acc02001_list.do\", \"#main\", \"#divListData\", function() {\r\n");
      out.write("\t\t\tvar cust_cd = $(\"tr[id='tr_0']\").attr(\"cust_cd\");\r\n");
      out.write("\t\t\tif(cust_cd != undefined) { goEdit(cust_cd); }\r\n");
      out.write("\t\t\tfixTableHeader(\"MyTable\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goWrite() {\r\n");
      out.write("\t\t$(\"tr[id^='tr_']\").removeClass(\"bg-yellow\");\r\n");
      out.write("\t\tajaxReplaceForm(\"acc02002_write.do\", \"#main\", \"#divFrame\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goEdit(cust_cd) {\r\n");
      out.write("\t\t$(\"tr[id^='tr_']\").removeClass(\"bg-yellow\");\r\n");
      out.write("\t\tif(cust_cd != '') { $(\"tr[cust_cd='\"+cust_cd+\"']\").addClass(\"bg-yellow\"); }\r\n");
      out.write("\t\tvar pageUrl = 'acc02002_edit.do?cust_cd='+cust_cd;\r\n");
      out.write("\t\tajaxReplaceForm(pageUrl, \"#main\", \"#divFrame\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t");
 if(rsWp.getLength() < 1) { 
      out.write("\r\n");
      out.write("\t\t\tgoWrite();\r\n");
      out.write("\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t\tvar cust_cd = ");
      out.print(rsWp.get("cust_cd",0));
      out.write("\r\n");
      out.write("\t\t\t$(\"tr[cust_cd='\"+cust_cd+\"']\").addClass(\"bg-yellow\");\r\n");
      out.write("\t\t\tgoEdit(cust_cd);\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\tfixTableHeader(\"MyTable\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form id=\"main\" name=\"main\" method=\"post\" action=\"\" class=\"fType\" style=\"margin:0px\">\r\n");
      out.write("<input type=\"hidden\" name=\"cust_cd\" \t\tvalue=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"page_count\"\t\tvalue=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"selectedRow\" \tvalue=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"excel_file_nm\" \tvalue=\"거래처코드\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 class=\"page-title\">거래처코드</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"search-panel table table-bordered\">\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" style=\"width:12%\">거래처유형</td>\r\n");
      out.write("\t\t\t\t<td style=\"width:12%\">\r\n");
      out.write("\t\t\t\t\t<select name=\"cust_type\" class=\"bs-select form-control\" style=\"width:100px\">\r\n");
      out.write("\t\t\t\t\t\t<option value=''>전체</option>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(CodeUtil.optList("PR_COMTB_CODE02_LIST","LISTCODE",box.get("cust_type"),"cust_type","","","",""));
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\">\r\n");
      out.write("\t\t\t\t\t<select name=\"search_key\" class=\"bs-select form-control\" style=\"width:95%\">\r\n");
      out.write("\t\t\t\t\t\t<option value='1' ");
      out.print(box.get("search_key").equals("1")?"selected":"");
      out.write(">거래처명</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='2' ");
      out.print(box.get("search_key").equals("2")?"selected":"");
      out.write(">사업자번호</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='3' ");
      out.print(box.get("search_key").equals("3")?"selected":"");
      out.write(">주민등록번호</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='4' ");
      out.print(box.get("search_key").equals("4")?"selected":"");
      out.write(">대표자성명</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='5' ");
      out.print(box.get("search_key").equals("5")?"selected":"");
      out.write(">담당자성명</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"search_val\" value=\"");
      out.print(box.get("search_val"));
      out.write("\" class=\"form-control\" style=\"width:200px;ime-mode:active;display:");
      out.print(box.get("search_key").equals("6")?"none":"");
      out.write("\" onkeydown=\"if(event.keyCode == 13) goSearch('');\">\r\n");
      out.write("\t\t\t\t\t<label class=\"mt-checkbox mt-checkbox-outline\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"use_flag\" value=\"N\" ");
      out.print(box.get("use_flag").equals("N")?"checked":"");
      out.write(" style=\"border:none\">삭제코드 포함<span/>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t<span class=\"f-right marR60\">\r\n");
      out.write("\t\t\t  \t\t\t<button type=\"button\" class=\"btn btn-primary\" onClick=\"goSearch('');\"><img src=\"/com/img/ico_btn_search.png\">검색</button>\r\n");
      out.write("\t\t  \t\t\t");
if(uSesEnt.use_auth.startsWith("S")||uSesEnt.use_auth.equals("GA")){
      out.write("\r\n");
      out.write("\t\t  \t\t\t\t<button type=\"button\" id=\"btnExcel\" class=\"btn btn-primary\" onclick=\"goExcel();\"><img src=\"/com/img/ico_btn_excel.png\">엑셀</button>\r\n");
      out.write("\t  \t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t<button type=\"button\" class=\"btn dark\" onClick=\"goWrite();\"><img src=\"/com/img/ico_btn_refresh_edit.png\">새로작성</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<div id=\"divListData\" class=\"contentsRow\">\t\t\r\n");
 } 
      out.write("\r\n");
      out.write("\t<div class=\"row row-set\">\r\n");
      out.write("\t\t<div class=\"col-md-4 col-xs-4 col-sm-4 row-set-col padL0 padR0\">\r\n");
      out.write("\t\t\t<div class=\"table-scrollable scrollOptionY\" style=\"width:100%; height:calc(100vh - 140px);\">\r\n");
      out.write("\t\t\t\t<table id=\"MyTable\" class=\"table table-striped table-bordered table-hover order-column\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t");
 if(!box.get("excel_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th>거래처명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>사업자번호</th>\r\n");
      out.write("\t\t\t\t\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th>코드</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>거래처명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>사업자번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>대표자</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>업태</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>종목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>우편번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>주소</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t          \t\t</tr>\r\n");
      out.write("\t\t          \t</thead>\r\n");
      out.write("\t\t          \t<tbody> \r\n");
      out.write("\t\t\t\t\t");
 if(rsWp.getLength() == 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"25\"><td colspan=\"2\" class=\"t-center\">등록된 자료가 없습니다.</td></tr>\r\n");
      out.write("\t\t\t\t\t");
 }else {
				   			for(int i=0; i < rsWp.getLength(); i++) {	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(!box.get("excel_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr id=\"tr_");
      out.print(i);
      out.write("\" height=\"25\" cust_cd=\"");
      out.print(rsWp.get("cust_cd",i));
      out.write("\" style=\"cursor:pointer\" onClick=\"goEdit('");
      out.print(rsWp.get("cust_cd",i));
      out.write("')\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-left\">");
      out.print(rsWp.get("cust_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-center\">");
      out.print(FormatUtil.bizRegiNoFormat(rsWp.get("cust_reg_no",i)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr height=\"25\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-center\" style=\"mso-number-format:\\@;\">");
      out.print(rsWp.get("cust_cd",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(rsWp.get("cust_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-center\">");
      out.print(rsWp.get("cust_flag",i).equals("1") ? FormatUtil.bizRegiNoFormat(rsWp.get("cust_reg_no",i)) : FormatUtil.juminNo(rsWp.get("cust_reg_no",i),"x"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-center\">");
      out.print(rsWp.get("rep_person_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-center\">");
      out.print(rsWp.get("uptae",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-center\">");
      out.print(rsWp.get("upjong",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-center\">");
      out.print(rsWp.get("zip_no",i,Box.ZIP_CODE));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(rsWp.get("addr",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"t-center\">");
      out.print(rsWp.get("tel_no",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\t \t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t");
 if(!box.get("excel_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("\t\t\t");
      out.print(PageUtil.makePaging(box, rsWp, 30, 5, "COUNT", request));
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-8 col-xs-8 col-sm-8 row-set-col\">\r\n");
      out.write("\t\t\t<div id=\"divFrame\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
 if(!box.get("ajax_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
