/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-20 07:29:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class slp11001_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.RsWrapper rsWp = null;
      rsWp = (egovframework.cbiz.RsWrapper) _jspx_page_context.getAttribute("rsWp", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (rsWp == null){
        rsWp = new egovframework.cbiz.RsWrapper();
        _jspx_page_context.setAttribute("rsWp", rsWp, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
 RsWrapper codeWp = CodeUtil.getRsWrapper("PR_COMTB_CODE02_LIST","MULTCODE", "", "biz_type|sign_status|","","","","",uSesEnt.dbo); 
      out.write("\r\n");
      out.write("<!-- 전표현황 조회 -->\r\n");
      out.write("\r\n");
 if(!box.get("ajax_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("\tfunction goSearch(gbn) {\r\n");
      out.write("\t\tif(formValidate(\"#main\")) {\r\n");
      out.write("\t\t\tvar pageUrl = 'slp11001_list.do';\r\n");
      out.write("\t\t\tif(gbn == 'E') { \r\n");
      out.write("\t\t\t\tif(confirm('엑셀파일로 다운로드받으시겠습니까?')) {\r\n");
      out.write("\t\t\t\t\tpageUrl += '?excel_yn=P&excel_form_no=SLP11001';\r\n");
      out.write("\t\t\t\t\tajaxSubmitForm(pageUrl,\"#main\", function(rtn) {\r\n");
      out.write("\t\t\t\t\t\thideServerWorking();\r\n");
      out.write("\t\t\t\t\t\tif(rtn.isOk == \"Y\") {\r\n");
      out.write("\t\t\t\t\t\t\tpoiExcelDownload(rtn.excelPath);\r\n");
      out.write("\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\talert(rtn.errMsg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.main.page_count.value = '';\r\n");
      out.write("\t\t\tajaxReplaceForm(pageUrl, \"#main\", \"#divListData\", function() {\r\n");
      out.write("\t\t\t\tfixTableHeader(\"MyTable\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction goPage(page_count) {\r\n");
      out.write("\t\tdocument.main.page_count.value = page_count;\r\n");
      out.write("\t\tajaxReplaceForm(\"slp11001_list.do\", \"#main\", \"#divListData\", function() {\r\n");
      out.write("\t\t\tfixTableHeader(\"MyTable\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction __Calendar_Setting_Post(target) {\r\n");
      out.write("\t\tif(!isEmpty(document.main.slip_ymd)) {\r\n");
      out.write("\t\t\tdocument.main.slip_no.options.length = 0;\r\n");
      out.write("\t\t\tvar slip_ymd = document.main.slip_ymd.value.replace(/-/g,\"\");\r\n");
      out.write("\t\t\tvar dept_cd = '");
      out.print(uSesEnt.use_auth.startsWith("S")? "" : uSesEnt.dept_cd);
      out.write("';\r\n");
      out.write("\t\t\tsetOptionByProc('PR_ACCTB_SLIP01_LIST@LISTCODE', document.main.slip_no, '', slip_ymd, '', dept_cd, '', '', '선택');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goSort(sort_order) {\r\n");
      out.write("\t\tdocument.main.sort_order.value = sort_order;\r\n");
      out.write("\t\tgoSearch('N');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeSearchKey(search_key) {\r\n");
      out.write("\t\tif(search_key == 4) {\r\n");
      out.write("\t\t\t$(\"#search_val\").addClass(\"tNUM\");\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\t$(\"#search_val\").removeClass(\"tNUM\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tfixTableHeader(\"MyTable\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form id=\"main\" name=\"main\" method=\"post\" action=\"\" class=\"fType\" style=\"margin:0px\">\r\n");
      out.write("<input type=\"hidden\" name=\"sort_order\"  \tvalue=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"excel_file_nm\"\tvalue=\"전표현황조회\">\r\n");
      out.write("<input type=\"hidden\" name=\"page_count\"\t\tvalue=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 class=\"page-title\">전표현황 조회</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"search-panel table table-bordered\">\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t<col style=\"width:20%;\">\r\n");
      out.write("\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t<col style=\"width:20%;\">\r\n");
      out.write("\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t<col style=\"width:30%;\">\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t  \t\t<tr>\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<select name=\"ymd_flag\" class=\"bs-select form-control\" style=\"width:90%\">\r\n");
      out.write("\t\t\t\t\t\t<option value='1' ");
      out.print(box.get("ymd_flag").equals("1")?"selected":"");
      out.write(">전표일자</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='2' ");
      out.print(box.get("ymd_flag").equals("2")?"selected":"");
      out.write(">회계일자</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t<td nowrap>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group input-medium date date-picker\" data-date=\"");
      out.print(box.get("start_ymd",Box.DEF_DATE_FMT));
      out.write("\" data-date-format=\"yyyy-mm-dd\" data-date-viewmode=\"years\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"start_ymd\" name=\"start_ymd\" value=\"");
      out.print(box.get("start_ymd"));
      out.write("\" maxlength=\"8\" title=\"전표일자(부터)\" class=\"form-control tYMD\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-btn\"><button class=\"btn dark\" type=\"button\"><i class=\"fa fa-calendar\"></i></button></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span> ~ </span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group input-medium date date-picker\" data-date=\"");
      out.print(box.get("end_ymd",Box.DEF_DATE_FMT));
      out.write("\" data-date-format=\"yyyy-mm-dd\" data-date-viewmode=\"years\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"end_ymd\" name=\"end_ymd\" value=\"");
      out.print(box.get("end_ymd"));
      out.write("\" maxlength=\"8\" title=\"전표일자(까지)\" class=\"form-control tYMD\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-btn\"><button class=\"btn dark\" type=\"button\"><i class=\"fa fa-calendar\"></i></button></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th>작성부서</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t");
 if(uSesEnt.use_auth.startsWith("S")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<select name=\"dept_cd\" title=\"작성부서\" class=\"bs-select form-control\" style=\"width:200px\" onChange=\"if(this.value.length > 1) goSearch('N');\">\r\n");
      out.write("\t\t\t\t\t\t<option value='*'>전체</option>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(CodeUtil.optList("PR_INSTB_DEPT01_LIST","LISTCODE",box.get("dept_cd"),"","","","","Y",uSesEnt.dbo));
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.print(uSesEnt.dept_nm);
      out.write("<input type=\"hidden\" name=\"dept_cd\"  value=\"");
      out.print(uSesEnt.dept_cd);
      out.write("\">\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th>업무유형</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"biz_type\" class=\"bs-select form-control\" style=\"width:150px\">\r\n");
      out.write("\t\t\t\t\t\t<option value=''>전체</option>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(CodeUtil.optList(codeWp, "biz_type", box.get("biz_type")));
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t  \t\t</tr>\r\n");
      out.write("\t  \t\t<tr>\r\n");
      out.write("\t\t\t\t<th>전표번호</th>\r\n");
      out.write("\t\t\t\t<td nowrap>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group input-medium date date-picker\" data-date=\"");
      out.print(box.get("slip_ymd",Box.DEF_DATE_FMT));
      out.write("\" data-date-format=\"yyyy-mm-dd\" data-date-viewmode=\"years\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"slip_ymd\" name=\"slip_ymd\" value=\"");
      out.print(box.get("slip_ymd"));
      out.write("\" maxlength=\"8\" title=\"전표일자\" class=\"form-control tYMD\" onChange=\"__Calendar_Setting_Post('')\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-btn\"><button class=\"btn dark\" type=\"button\"><i class=\"fa fa-calendar\"></i></button></span>\r\n");
      out.write("\t\t\t\t\t\t</div> ~\r\n");
      out.write("\t\t\t\t\t\t<select name=\"slip_no\" title=\"전표번호\" class=\"bs-select form-control\" style=\"width:90px\" onChange=\"goSearch();\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=''>선택</option>\r\n");
      out.write("\t\t\t\t\t\t");
 if(!box.get("slip_ymd").equals("")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(CodeUtil.optList("PR_ACCTB_SLIP01_LIST","LISTCODE",box.get("slip_no"),box.get("slip_ymd"),"","","","",uSesEnt.dbo));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th>결재상태</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"sign_status\" class=\"bs-select form-control\" style=\"width:90px\">\r\n");
      out.write("\t\t\t\t\t\t<option value=''>전체</option>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(CodeUtil.optList(codeWp, "sign_status", box.get("sign_status")));
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<select name=\"search_key\" class=\"bs-select form-control\" style=\"width:90%\" onChange=\"changeSearchKey(this.value)\">\r\n");
      out.write("\t\t\t\t\t\t<option value='1' ");
      out.print(box.get("search_key").equals("1")?"selected":"");
      out.write(">작성자</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='2' ");
      out.print(box.get("search_key").equals("2")?"selected":"");
      out.write(">작성부서</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='3' ");
      out.print(box.get("search_key").equals("3")?"selected":"");
      out.write(">적요</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='4' ");
      out.print(box.get("search_key").equals("4")?"selected":"");
      out.write(">금액</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"search_val\" name=\"search_val\" value=\"");
      out.print(box.get("search_val"));
      out.write("\" class=\"form-control\" style=\"width:150px;ime-mode:active;\" onkeydown=\"if(event.keyCode == 13) goSearch('N')\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t  \t\t</tr>\r\n");
      out.write("\t  \t</tbody>\r\n");
      out.write("\t</table>\t\t    \r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<div id=\"divListData\" class=\"contentsRow\">\r\n");
 } 
      out.write("\r\n");
      out.write("\t<div class=\"table-top-control form-inline\">\r\n");
      out.write("\t\t<div class=\"notice-view\">\r\n");
      out.write("\t\t\t<span style=\"color:#01a1db;\">문서번호, 전표번호를 클릭</span>하면 해당 세부내용을 조회할 수 있습니다.\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<span class=\"f-right\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary\" onClick=\"goSearch('N');\"><img src=\"/com/img/ico_btn_search.png\">검색</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary\" onClick=\"goSearch('E');\"><img src=\"/com/img/ico_btn_excel.png\">엑셀</button>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"divArea\" class=\"table-scrollable scrollOptionY\" style=\"height:calc(100vh - 200px)\">\r\n");
      out.write("\t\t<table id=\"MyTable\" class=\"table table-striped table-bordered table-hover order-column\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col style=\"width:3%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:8%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:9%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:19%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:6%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:6%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:9%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:6%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:6%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:6%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:6%;\">\r\n");
      out.write("\t\t\t\t<col style=\"width:6%;\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>No</th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.msg_no')\">");
}
      out.write("문서번호</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.slip_no')\">");
}
      out.write("전표번호</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.biz_type')\">");
}
      out.write("업무유형</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.subject')\">");
}
      out.write("적요</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.cha_amt')\">");
}
      out.write("차변금액</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.dae_amt')\">");
}
      out.write("대변금액</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.dept_cd')\">");
}
      out.write("작성부서</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.empl_no')\">");
}
      out.write("작성자</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.sys_reg_date desc')\">");
}
      out.write("작성일자</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.acc_unit')\">");
}
      out.write("회계단위</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.sign_ymd desc')\">");
}
      out.write("회계일자</a></th>\r\n");
      out.write("\t\t\t\t\t<th>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSort('t1.sign_status')\">");
}
      out.write("결재상태</a></th>\r\n");
      out.write("    \t\t\t</tr>\r\n");
      out.write("    \t\t</thead>\r\n");
      out.write("    \t\t<tbody> \r\n");
      out.write("\t\t\t");
 if(rsWp.getLength() == 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t<tr><td colspan=\"13\">등록된 자료가 없습니다.</td></tr>\r\n");
      out.write("\t\t\t");
 }else {
		   		for(int i=0; i < rsWp.getLength(); i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(box.get("excel_yn").equals("Y") ? String.valueOf(i+1) : rsWp.get("row_num",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goDocuViewer('");
      out.print(rsWp.get("msg_no",i));
      out.write("')\">");
}
      out.print(FormatUtil.msgNo(rsWp.get("msg_no",i)));
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t<td>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goSlipViewer('&slip_no=");
      out.print(rsWp.get("slip_no",i));
      out.write("')\">");
}
      out.print(rsWp.get("slip_no",i,Box.SLIP_NO));
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rsWp.get("biz_type_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"t-left\">");
      out.print(rsWp.get("subject",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"t-right\">");
      out.print(rsWp.get("cha_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"t-right\">");
      out.print(rsWp.get("dae_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rsWp.get("dept_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
if(!box.get("excel_yn").equals("Y")){
      out.write("<a href=\"javascript:goEmployeePop('");
      out.print(rsWp.get("empl_no",i));
      out.write("')\">");
}
      out.print(rsWp.get("empl_nm",i));
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rsWp.get("sys_reg_date",i,Box.DEF_DATE_FMT));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rsWp.get("acc_unit_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rsWp.get("sign_ymd",i,Box.DEF_DATE_FMT));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td><a title=\"");
      out.print(rsWp.get("reject_reason",i));
      out.write('"');
      out.write('>');
      out.print(rsWp.get("sign_status_nm",i));
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t   \t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.print(PageUtil.makePaging(box, rsWp, 30, request));
      out.write('\r');
      out.write('\n');
 if(!box.get("ajax_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
