/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-27 02:29:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class slp21001_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.Box obox = null;
      obox = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("obox", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obox == null){
        obox = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("obox", obox, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.RsWrapper rsWp = null;
      rsWp = (egovframework.cbiz.RsWrapper) _jspx_page_context.getAttribute("rsWp", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (rsWp == null){
        rsWp = new egovframework.cbiz.RsWrapper();
        _jspx_page_context.setAttribute("rsWp", rsWp, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<!-- 회계전표 수정 -->\t\r\n");
      out.write("\r\n");
 if(!box.get("ajax_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction goSearch() {\r\n");
      out.write("\t\tremoveMask(\"#main\");\r\n");
      out.write("\t\tdocument.main.action = \"slp21001.do\"; \r\n");
      out.write("\t\tdocument.main.target = \"_self\";\r\n");
      out.write("\t\tdocument.main.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goDetail(slip_seq) {\r\n");
      out.write("\t\t$(\"tr[id^='tr_']\").removeClass(\"bg-yellow\");\r\n");
      out.write("\t\tif(slip_seq != '') { $(\"tr[slip_seq='\"+slip_seq+\"']\").addClass(\"bg-yellow\"); }\r\n");
      out.write("\t\tvar pageUrl = 'slp21002_edit.do?slip_seq='+slip_seq;\r\n");
      out.write("\t\tajaxReplaceForm(pageUrl, \"#main\", \"#divFrame\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goSave() {\r\n");
      out.write("\t\tif(formValidate(\"#main\")) {\r\n");
      out.write("\t\t\tif(confirm('결산반영일 또는 회계단위를 수정하시겠습니까?')) {\r\n");
      out.write("\t\t\t\tremoveMask(\"#main\");\r\n");
      out.write("\t\t\t\tdocument.main.action='slp21001_update.do';\r\n");
      out.write("\t\t\t\tdocument.main.target='_self';\r\n");
      out.write("\t\t\t\tdocument.main.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction __Calendar_Setting_Post(target) {\r\n");
      out.write("\t\tif(target == 'p_slip_ymd' && !isEmpty(document.main.p_slip_ymd)) {\r\n");
      out.write("\t\t\tdocument.main.p_slip_no.options.length = 0;\r\n");
      out.write("\t\t\tvar slip_ymd = document.main.p_slip_ymd.value.replace(/-/g,\"\");\r\n");
      out.write("\t\t\tsetOptionByProc('PR_ACCTB_SLIP01_LIST@LISTCODE', document.main.p_slip_no, '', slip_ymd, '', '', '', '', '선택');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t");
 if(rsWp.getLength() > 0) { 
      out.write("\r\n");
      out.write("\t\tgoDetail('");
      out.print(rsWp.get("slip_seq",0));
      out.write("');\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form id=\"main\" name=\"main\" method=\"post\" action=\"\" class=\"fType\" style=\"margin:0px\">\r\n");
      out.write("<input type=\"hidden\" name=\"slip_no\" \tvalue=\"");
      out.print(obox.get("slip_no"));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"biz_type\" \tvalue=\"");
      out.print(obox.get("biz_type"));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"selectedRow\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 class=\"page-title\">회계전표 수정</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"search-panel table table-bordered\">\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t<col style=\"width:20%;\">\r\n");
      out.write("\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t<col style=\"width:20%;\">\r\n");
      out.write("\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t<col style=\"width:30%;\">\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t  \t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\">전표번호</td>\r\n");
      out.write("\t\t\t\t<td nowrap>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline\"><!-- onBlur=\"__Calendar_Setting_Post('')\" -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group input-medium date date-picker\" data-date=\"");
      out.print(box.get("p_slip_ymd",Box.DEF_DATE_FMT));
      out.write("\" data-date-format=\"yyyy-mm-dd\" data-date-viewmode=\"years\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"p_slip_ymd\" name=\"p_slip_ymd\" value=\"");
      out.print(box.get("p_slip_ymd"));
      out.write("\" maxlength=\"8\" title=\"전표일자\" class=\"form-control required tYMD\" onchange=\"__Calendar_Setting_Post('p_slip_ymd')\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-btn\"><button class=\"btn dark\" type=\"button\"><i class=\"fa fa-calendar\"></i></button></span>\r\n");
      out.write("\t\t\t\t\t\t</div> ~\r\n");
      out.write("\t\t\t\t\t\t<select name=\"p_slip_no\" title=\"전표번호\" class=\"bs-select form-control required\" style=\"width:90px\" onChange=\"goSearch();\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=''>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(CodeUtil.optList("PR_ACCTB_SLIP01_LIST","LISTCODE",box.get("p_slip_no"),box.get("p_slip_ymd"),"","","","",uSesEnt.dbo));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\">작성부서</td>\r\n");
      out.write("\t\t\t\t<td nowrap>");
      out.print(obox.get("dept_nm"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\">작성자</td>\r\n");
      out.write("\t\t\t\t<td nowrap>");
      out.print(obox.get("empl_nm"));
      out.write("</td>\r\n");
      out.write("\t  \t\t</tr>\r\n");
      out.write("\t  \t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\">결재상태</td>\r\n");
      out.write("\t\t\t\t<td nowrap><b><font color=red>");
      out.print(obox.get("sign_status_nm"));
      out.write("</font></b>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t");
 if(obox.get("sign_status").compareTo("1") > 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-table\" onClick=\"goDocuViewer('");
      out.print(obox.get("msg_no"));
      out.write("');\">기안문보기</button>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t");
 if(obox.get("sign_status").equals("3") && !obox.get("sign_ymd").equals("")) { 
      out.write("\r\n");
      out.write("\t\t\t\t<td class=\"td-head\">회계전표번호</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" nowrap>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group input-medium date date-picker\" data-date=\"");
      out.print(obox.get("sign_ymd",Box.DEF_DATE_FMT));
      out.write("\" data-date-format=\"yyyy-mm-dd\" data-date-viewmode=\"years\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"sign_ymd\" value=\"");
      out.print(obox.get("sign_ymd"));
      out.write("\" maxlength=\"8\" title=\"결산반영일\" class=\"form-control required tYMD\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-btn\"><button class=\"btn dark\" type=\"button\"><i class=\"fa fa-calendar\"></i></button></span>\r\n");
      out.write("\t\t\t\t\t\t</div> -\r\n");
      out.write("\t\t\t\t\t\t<select name=\"p_acc_unit\" class=\"bs-select form-control required\" title=\"회계단위\" style=\"width:97px\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value='00' ");
      out.print(obox.get("acc_unit").equals("00")?"selected":"");
      out.write(">목적사업</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value='20' ");
      out.print(obox.get("acc_unit").equals("20")?"selected":"");
      out.write(">기금관리</option>\r\n");
      out.write("\t\t\t\t\t\t</select> - \r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"p_sign_no\" value=\"");
      out.print(obox.get("sign_no"));
      out.write("\" class=\"form-control\" style=\"width:45px\" readOnly>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-table\" onClick=\"goSave()\">수정</button>\r\n");
      out.write("\t\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t\t\t<td class=\"td-head\">작성일자</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" nowrap>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline\">");
      out.print(obox.get("sys_reg_date",Box.DEF_DATETIME_FMT_APM));
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span class=\"f-right marR60\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn dark\" onClick=\"goUbiViewer('WEB-INF/jsp/account/report/slp01001.jrf','P_PARAM01!SLP009,");
      out.print(obox.get("slip_no"));
      out.write("!P_PARAM02!,ACCTB_SLIP01|");
      out.print(obox.get("slip_no"));
      out.write("!')\"><img src=\"/com/img/ico_btn_print.png\">인쇄</button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t  \t</tbody>\r\n");
      out.write("\t</table>\t\r\n");
      out.write("</form>\t\r\n");
      out.write("\r\n");
      out.write("<div id=\"divListData\" class=\"contentsRow\">\r\n");
 } 
      out.write("\r\n");
      out.write("\t<div class=\"row row-set\">\r\n");
      out.write("\t\t<div class=\"col-md-6 col-xs-6 col-sm-6 row-set-col padL0 padR0\">\r\n");
      out.write("\t\t\t<div id=\"divChaArea\" class=\"table-scrollable scrollOptionY\" style=\"height:300px\">\r\n");
      out.write("\t\t\t\t<table id=\"chaListTable\" class=\"table table-striped table-bordered table-hover order-column\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><span style=\"color:#01a1db;\">차&nbsp;&nbsp;&nbsp;변</span></th>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t[<input type=\"text\" name=\"cha_cnt\" value=\"");
      out.print(obox.get("cha_cnt"));
      out.write("\" class=\"form-control acc-border tMONEY\" style=\"width:30px;height:16px\" readOnly> 건],&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t[<input type=\"text\" name=\"cha_amt\" value=\"");
      out.print(obox.get("cha_amt"));
      out.write("\" class=\"form-control acc-border tMONEY\" style=\"width:100px;height:16px\" readOnly> 원]\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\">계정과목</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"20%\">금액</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"50%\">적요</th>\r\n");
      out.write("\t          \t\t</tr> \r\n");
      out.write("\t\t\t\t");
 if(rsWp.getLength() == 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr><td colspan=\"3\" class=\"t-center\">등록된 자료가 없습니다.</td></tr>\r\n");
      out.write("\t\t\t\t");
 }else {
			   		for(int i=0; i < rsWp.getLength(); i++) { if(!rsWp.get("cd_flag",i).equals("1")) { continue; } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"tr_");
      out.print(i);
      out.write("\" slip_seq=\"");
      out.print(rsWp.get("slip_seq",i));
      out.write("\" style=\"cursor:pointer\" onClick=\"goDetail('");
      out.print(rsWp.get("slip_seq",i));
      out.write("')\"> \r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(rsWp.get("acct_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(rsWp.get("slip_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(rsWp.get("etc_remark",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t    ");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"divDaeArea\" class=\"table-scrollable scrollOptionY\" style=\"height:300px\">\r\n");
      out.write("\t\t\t\t<table id=\"daeListTable\" class=\"table table-striped table-bordered table-hover order-column\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><span style=\"color:#01a1db;\">대&nbsp;&nbsp;&nbsp;변</span></th>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t[<input type=\"text\" name=\"dae_cnt\" value=\"");
      out.print(obox.get("dae_cnt"));
      out.write("\" class=\"form-control acc-border tMONEY\" style=\"width:30px;height:16px\" readOnly> 건],&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t[<input type=\"text\" name=\"dae_amt\" value=\"");
      out.print(obox.get("dae_amt"));
      out.write("\" class=\"form-control acc-border tMONEY\" style=\"width:100px;height:16px\" readOnly> 원]\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\">계정과목</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"20%\">금액</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"50%\">적요</th>\r\n");
      out.write("\t          \t\t</tr> \r\n");
      out.write("\t\t\t\t");
 if(rsWp.getLength() == 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr><td colspan=\"3\" class=\"t-center\">등록된 자료가 없습니다.</td></tr>\r\n");
      out.write("\t\t\t\t");
 }else {
			   		for(int i=0; i < rsWp.getLength(); i++) { if(!rsWp.get("cd_flag",i).equals("2")) { continue; } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"tr_");
      out.print(i);
      out.write("\" slip_seq=\"");
      out.print(rsWp.get("slip_seq",i));
      out.write("\" style=\"cursor:pointer\" onClick=\"goDetail('");
      out.print(rsWp.get("slip_seq",i));
      out.write("')\"> \r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(rsWp.get("acct_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(rsWp.get("slip_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(rsWp.get("etc_remark",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-6 col-xs-6 col-sm-6 row-set-col\">\r\n");
      out.write("\t\t\t<div id=\"divFrame\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
 if(!box.get("ajax_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
