/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-20 07:24:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.finance;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class fin13003_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.Box obox = null;
      obox = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("obox", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obox == null){
        obox = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("obox", obox, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.RsWrapper rsWp = null;
      rsWp = (egovframework.cbiz.RsWrapper) _jspx_page_context.getAttribute("rsWp", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (rsWp == null){
        rsWp = new egovframework.cbiz.RsWrapper();
        _jspx_page_context.setAttribute("rsWp", rsWp, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
	RsWrapper chaWp = new RsWrapper();
	RsWrapper daeWp = new RsWrapper();
	Box daeBox = null;
	for(int i=0; i < rsWp.getLength(); i++) {
		if(rsWp.get("acct_cd",i).startsWith("11101") || rsWp.get("acct_cd",i).startsWith("11103") || rsWp.get("acct_cd",i).startsWith("11105")) { // 예금
			if(daeBox != null) { 
				daeWp.appendRs(daeBox); 
				daeBox = null;
			}
			
			if(rsWp.get("cd_flag",i).equals("1")) {
				chaWp.appendRs(rsWp.getRsBoxAt(i));
			}else if(rsWp.get("cd_flag",i).equals("2")) {
				daeBox = rsWp.getRsBoxAt(i);
			}
		}else if(rsWp.get("acct_cd",i).startsWith("61")) { // 이자수익
			daeBox.put("intr_amt", rsWp.get("slip_amt",i));
		}else if(rsWp.get("acct_cd",i).startsWith("1110901")) { // 선급법인세(법인세)
			daeBox.put("ltax_amt", rsWp.get("slip_amt",i));
			daeBox.put("tax_rate", rsWp.get("tax_rate",i));
		}else if(rsWp.get("acct_cd",i).startsWith("1110902")) { // 선급법인세(지방세)
			daeBox.put("ljum_amt", rsWp.get("slip_amt",i));
		}
	}
	if(daeBox != null) { daeWp.appendRs(daeBox); }

      out.write("\r\n");
      out.write("<!-- 예적금이체 -->\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form id=\"viewForm\" name=\"viewForm\" method=\"post\" class=\"fType\" action=\"\" style=\"margin:0px\">\r\n");
      out.write("<input type=\"hidden\" name=\"slip_no\"\t\tvalue=\"");
      out.print(obox.get("slip_no"));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t<table class=\"table table-view table-bordered\">\r\n");
      out.write("\t  \t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan=\"4\">예적금이체</th>\r\n");
      out.write("\t  \t\t</tr>\r\n");
      out.write("\t  \t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"17%\">적요</th>\r\n");
      out.write("\t\t\t\t<td width=\"41%\">");
      out.print(obox.get("subject"));
      out.write("<input type=\"hidden\" name=\"subject_no\" value=\"");
      out.print(obox.get("subject"));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t<th width=\"17%\">이체일자</th>\r\n");
      out.write("\t\t\t\t<td width=\"25%\">");
      out.print(obox.get("proof_ymd",Box.DEF_DATE_FMT));
      out.write("</td>\r\n");
      out.write("\t  \t\t</tr>\r\n");
      out.write("\t  \t\t<tr>\r\n");
      out.write("\t\t\t\t<th>결재상태</th>\r\n");
      out.write("\t\t\t\t<td nowrap><b><font color=red>");
      out.print(obox.get("sign_status_nm"));
      out.write("</font></b>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t");
 if(obox.get("sign_status").compareTo("1") > 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-table\" onClick=\"goSignLine('','SLP011','ACCTB_SLIP01|");
      out.print(obox.get("slip_no"));
      out.write("');\">결재라인</button>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th>전표번호</th>\r\n");
      out.write("\t\t\t\t<td nowrap>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:goSlipViewer('&slip_no=");
      out.print(obox.get("slip_no"));
      out.write("');\">");
      out.print(obox.get("slip_no",Box.SLIP_NO));
      out.write("</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t  \t\t</tr>\r\n");
      out.write("\t\t</table>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<h2 class=\"page-title-2depth form-inline\">출금내역\r\n");
      out.write("\t\t<span id=\"dae_summary\" class=\"marL10\">\r\n");
      out.write("\t\t[<input type=\"text\" name=\"dae_cnt\" value=\"");
      out.print(daeWp.getLength());
      out.write("\" class=\"form-control acc-border tNUM\" style=\"width:24px;height:16px\" readOnly> 건],&nbsp;&nbsp;\r\n");
      out.write("\t\t[<input type=\"text\" name=\"dae_amt\" value=\"");
      out.print(obox.getLong("dae_amt"));
      out.write("\" class=\"form-control acc-border tMONEY\" style=\"width:100px;height:16px\" readOnly> 원]\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</h2>\t\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"table-scrollable scrollOptionY\" style=\"height:calc(200px)\">\r\n");
      out.write("\t\t<table id=\"daeTable\" class=\"table table-view table-bordered\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"18%\">예적금유형</th>\r\n");
      out.write("\t\t\t\t<th width=\"25%\">계좌번호</th>\r\n");
      out.write("\t\t\t\t<th width=\"13%\">출금액</th>\r\n");
      out.write("\t\t\t\t<th width=\"13%\">이자수익</th>\r\n");
      out.write("\t\t\t\t<th width=\"5%\">세율<br>(%)</th>\r\n");
      out.write("\t\t\t\t<th width=\"13%\">선급법인세<br>(법인세)</th>\r\n");
      out.write("\t\t\t\t<th width=\"13%\">선급법인세<br>(지방세)</th>\r\n");
      out.write("         \t</tr> \r\n");
      out.write("         \t");
 for(int i=0; i < daeWp.getLength(); i++) { 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(daeWp.get("acct_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(daeWp.get("bank_nm",i));
      out.write(' ');
      out.print(daeWp.get("rel_no",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\">");
      out.print(daeWp.get("slip_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\">");
      out.print(daeWp.get("intr_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\">");
      out.print(daeWp.get("tax_rate",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\">");
      out.print(daeWp.get("ltax_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\">");
      out.print(daeWp.get("ljum_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("         \t</tr> \r\n");
      out.write("        \t");
 } 
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t<h2 class=\"page-title-2depth form-inline\">입금내역\r\n");
      out.write("\t\t<span id=\"cha_summary\" class=\"marL10\">\r\n");
      out.write("\t\t[<input type=\"text\" name=\"cha_cnt\" value=\"");
      out.print(chaWp.getLength());
      out.write("\" class=\"form-control acc-border tNUM\" style=\"width:24px;height:16px\" readOnly> 건],&nbsp;&nbsp;\r\n");
      out.write("\t\t[<input type=\"text\" name=\"cha_amt\" value=\"");
      out.print(obox.getLong("cha_amt"));
      out.write("\" class=\"form-control acc-border tMONEY\" style=\"width:100px;height:16px\" readOnly> 원]\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</h2>\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"table-scrollable scrollOptionY\" style=\"height:calc(200px)\">\r\n");
      out.write("\t\t<table id=\"chaTable\" class=\"table table-view table-bordered\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"18%\">예적금유형</th>\r\n");
      out.write("\t\t\t\t<th width=\"25%\">계좌번호</th>\r\n");
      out.write("\t\t\t\t<th width=\"13%\">입금액</th>\r\n");
      out.write("\t\t\t\t<th width=\"13%\"></th>\r\n");
      out.write("\t\t\t\t<th width=\"5%\"></th>\r\n");
      out.write("\t\t\t\t<th width=\"13%\"></th>\r\n");
      out.write("\t\t\t\t<th width=\"13%\"></th>\r\n");
      out.write("         \t</tr> \r\n");
      out.write("         \t");
 for(int i=0; i < chaWp.getLength(); i++) { 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(chaWp.get("acct_nm",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(chaWp.get("bank_nm",i));
      out.write(' ');
      out.print(chaWp.get("rel_no",i));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\">");
      out.print(chaWp.get("slip_amt",i,Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("         \t</tr> \r\n");
      out.write("         \t");
 } 
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"table-bottom-control\">\r\n");
      out.write("\t\t<span style=\"width:100%;\">\r\n");
      out.write("\t\t\t<span class=\"f-right\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn dark\" onClick=\"goUbiViewer('WEB-INF/jsp/account/report/slp01001.jrf','P_PARAM01!SLP009,");
      out.print(obox.get("slip_no"));
      out.write("!P_PARAM02!,ACCTB_SLIP01|");
      out.print(obox.get("slip_no"));
      out.write("!')\"><img src=\"/com/img/ico_btn_print.png\">인쇄</button>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
