/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-20 04:35:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.tax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class adj02003_005f3_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/com/include/excel_header.jsp", Long.valueOf(1568793281369L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.Box obox = null;
      obox = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("obox", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obox == null){
        obox = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("obox", obox, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.Box rbox = null;
      rbox = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("rbox", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (rbox == null){
        rbox = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("rbox", rbox, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
 String xmlBuf = ""; 
      out.write('\r');
      out.write('\n');
 if(box.get("excel_yn").equals("Y")) { 
      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
	
	String lm_sAgentType = request.getHeader("User-Agent"); 
	String excel_file_nm = box.get("excel_file_nm");
	excel_file_nm = StringUtil.get8859_1(excel_file_nm); // ìë²ììë ì£¼ìì²ë¦¬
	response.reset();
    if(lm_sAgentType.indexOf("MSIE 5.5") > -1 || lm_sAgentType.indexOf("MSIE 6.0") > -1) {
	    response.setHeader("Content-Type",        "doesn/matter;");
	    response.setHeader("Content-Disposition", "filename="+excel_file_nm+".xls");
    }else {
	    response.setHeader("Content-Type", "application/vnd.ms-excel;charset=UTF-8");
    	response.setHeader("Content-Disposition", "attachment;filename="+excel_file_nm+".xls");
	}
	response.setHeader("Content-Transfer-Encoding", "binary;");
	response.setHeader("Pragma", "no-cache;");
	response.setHeader("Expires", "-1;");

      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\ttd { font-size:12px; font-family:\"ë§ì ê³ ë\", \"Arial\", \"sans-serif\"; color:#00000; text-align:center; border:.5pt solid #000; }\n");
      out.write("</style>\n");
      out.write("<center><h2>");
      out.print(box.get("excel_file_nm"));
      out.write("</h2></center>");
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- [별지 제3호의3 서식(1)] 표준손익계산서(일반법인용) -->\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tajaxSubmitForm(\"xmlUpdate.do\",\"#taxForm\", function(rtn) {\r\n");
      out.write("\t\t\tif(rtn.isOk == \"Y\") {\r\n");
      out.write("\t\t\t\thideServerWorking();\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\talert(rtn.errMsg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
 if(!box.get("excel_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("<form id=\"taxForm\" name=\"taxForm\" method=\"post\" action=\"\" class=\"fType\">\r\n");
      out.write("<input type=\"hidden\" name=\"report_id\" \tvalue=\"");
      out.print(box.get("report_id"));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"std_yy\" \t\tvalue=\"");
      out.print(box.get("std_yy"));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<h2 class=\"page-title-2depths\">표준손익계산서(일반법인용)</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"table-top-control\">\r\n");
      out.write("\t\t<span style=\"float:right;\">[별지 제3호의3 서식(1)]</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"divListData\" class=\"contentsRow\">\r\n");
      out.write("\t\t<table class=\"table table-bordered order-column table-cover marB10\">\r\n");
      out.write("\t\t");
 xmlBuf += "<acc_start_ymd>"+obox.get("acc_start_ymd",Box.DEF_DATE_FMT)+"</acc_start_ymd>\n"
				  +  "<acc_end_ymd>"+obox.get("acc_end_ymd",Box.DEF_DATE_FMT)+"</acc_end_ymd>\n"
				  +  "<corp_nm>"+obox.get("corp_nm")+"</corp_nm>\n"
				  +  "<saupja_no>"+FormatUtil.bizRegiNoFormat(obox.get("saupja_no"))+"</saupja_no>\n"
				  +  "<code61_amt>" + rbox.get("code61_amt",Box.THOUSAND_COMMA) + "</code61_amt>\n"
				  +  "<code6100_amt>" + rbox.get("code6100_amt",Box.THOUSAND_COMMA) + "</code6100_amt>\n"
				  +  "<code6100301_amt>" + rbox.get("code6100301_amt",Box.THOUSAND_COMMA) + "</code6100301_amt>\n"
				  +  "<code6400101_amt>" + rbox.get("code6400101_amt",Box.THOUSAND_COMMA) + "</code6400101_amt>\n"
				  +  "<code6164_amt>" + rbox.get("code6164_amt",Box.THOUSAND_COMMA) + "</code6164_amt>\n"
				  +  "<code7500101_amt>" + rbox.get("code7500101_amt",Box.THOUSAND_COMMA) + "</code7500101_amt>\n"
				  +  "<code616475_amt>" + rbox.get("code616475_amt",Box.THOUSAND_COMMA) + "</code616475_amt>\n"; 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"25%\">계정과목</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"5%\">코드</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"20%\">금액</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"25%\">계정과목</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"5%\">코드</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"20%\">금액</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅰ.매출액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">1</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td stly=\"width:27%\" class=\"t-left padL15\">(7)지분법손실(지주회사)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">60</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">1.상품매출</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">2</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">(8)기타매출원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">61</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">가.국내상품매출</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">3</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">1.기초재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">62</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">나.수출상품매출</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">4</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">2.당기총원가(명세별첨)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">63</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">2.제품매출</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">5</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">3.기말재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">64</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">가.국내제품매출</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">6</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">4.타계정대체액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">65</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">나.수출제품매출</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">7</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅲ.매출총손익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">66</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">3.공사수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">8</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅳ.판매비와관리비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">67</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">가.국내공사수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">9</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">1.급여</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">68</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">나.해외공사수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">10</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.임원급여</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">69</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">4.운송수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">11</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.직원급여</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">70</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">가.국내운송수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">12</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">다.임원상여금</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">71</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">나.해외운송수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">13</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">라.직원상여금</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">72</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">5.부동산임대수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">14</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">마.기타</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">73</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">가.국내임대수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">15</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">2.퇴직급여</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">74</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">나.해외임대수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">16</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.임원퇴직급여</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">75</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">6.분양수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">17</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.직원퇴직급여</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">76</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">가.국내분양수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">18</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">다.퇴직급여충당부채전입액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">77</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">나.해외분양수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">19</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">3.보험료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">78</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">7.사용료·로열티 수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">20</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">4.복리후생비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">79</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">가.국내사용료·로열티수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">21</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">5.여비교통비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">80</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">나.해외사용료·로열티수입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">22</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">6.임차료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">81</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">8.지분법이익(지주회사)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">23</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.부동산임차료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">82</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">9.기타매출</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">24</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td stlye=\"width:27%\" class=\"t-left padL35\" >나.차량·중기임차료(리스료 포함)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">83</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">가.</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">25</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">다.기타임차료(리스료 포함)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">84</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅱ.매출원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">35</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">7.접대비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">85</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">(1)상품매출원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">36</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">8.유형자산감가상각비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">86</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">1.기초재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">37</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">9.무형자산상각비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">87</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">2.당기매입원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">38</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.영업권상각비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">88</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">3.상품관세환급금(-)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">39</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.기타무형자산상각비</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">89</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">4.기말재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">40</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">10.세금과공과</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">90</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">5.타계정대체액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">41</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">11.광고선전비(판매촉진비 포함)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">91</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">(2)제조원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">42</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">12.견본비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">92</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">1.기초재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">43</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">13.차량유지비(유류비 포함)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">93</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">2.당기총원가(명세별첨)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">44</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">14.연구비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">94</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">3.제품관세환급금(-)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">45</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">15.경상개발비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">95</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">4.기말재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">46</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td style=\"width:27%\" class=\"t-left padL25\">16.대손상각비(충당금전입액포함)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">96</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">5.타계정대체액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">47</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">17.미분양주택관리비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">97</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">(3)공사원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">48</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">18.수주비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">98</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">1.기초재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">49</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.국내수주비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">99</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">2.당기총원가(명세별첨)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">50</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.해외수주비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">100</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">3.기말재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">51</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">19.자문료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">101</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">4.타게정대체액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">52</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.국내자문료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">102</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">(4)운송원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">53</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.해외자문료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">103</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">(5)임대원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">54</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">20.지급수수료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">104</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL15\">(6)분양원가</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">55</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.국내지급수수료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">105</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">1.기초재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">56</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.해외지급수수료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">106</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">2.당기총원가(명세별첨)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">57</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">21.판매수수료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">107</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">3.기말재고액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">58</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">22.소모품비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">108</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">4.타계정대체액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">59</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">23.통신비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">109</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t<table class=\"table table-bordered order-column table-cover marB0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"25%\">계정과목</td>\r\n");
      out.write("\t\t\t\t<td width=\"5%\">코드</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\">금액</td>\r\n");
      out.write("\t\t\t\t<td width=\"25%\">계정과목</td>\r\n");
      out.write("\t\t\t\t<td width=\"5%\">코드</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\">금액</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">24.운반비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">110</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">22.수수료수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">164</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">25.보관료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">111</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.국내수수료수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">165</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">26.건물·시설관리비(수선비 제외)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">112</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.해외수수료수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">166</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">27.수선비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">113</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">23.사용료·로열티수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">167</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">28.수도광열비(전기료 제외)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">114</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.국내사용료·로열티수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">168</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">29.전기료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">115</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.해외사용료·로열티수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">169</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">30.인쇄비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">116</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">24.정부보조금</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">170</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">31.교육훈련비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">117</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">25.판매장려금수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">171</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">32.특허권등 사용료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">118</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">26.위약금·보상금·배상금 수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">172</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">33.수출입제비용</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">119</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">27.상각채권추심이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">173</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">34.해외시장개척비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">120</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">28.기타</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">174</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">35.기타외주용역비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">121</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅶ.영업외비용</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">179</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.국내외주용역비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">122</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">1.이자비용</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">180</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.해외외주용역비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">123</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">2.기타대손상각비</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">181</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">36.기타</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">124</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">3.유가증권처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">182</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅴ.영업손익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">129</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.단기매매증권처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">183</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅵ.영업외수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">130</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\">");
      out.print(rbox.get("code61_amt",Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.매도가능증권처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">184</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">1.이자수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">131</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\">");
      out.print(rbox.get("code6100_amt",Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width:27%\" class=\"t-left padL35\">다.지분법적용투자주식처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">185</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">2.배당금수익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">132</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\">");
      out.print(rbox.get("code6100301_amt",Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">4.매출채권처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">186</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">3.임대료</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">133</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">5.단기투자자산평가손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">187</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">4.유가증권처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">134</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">6.재고자산감모손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">188</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.단기매매증권처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">135</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">7.외환차손</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">189</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.매도가능증권처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">136</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">8.외화환산손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">190</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">다.지분법적용투자주식처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">137</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">9.지분법손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">191</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">5.매출채권처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">138</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">10.장기투자증권손상차손</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">192</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">6.단기투자자산평가이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">139</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.매도가능증권손상차손</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">193</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">7.외환차익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">140</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.만기보유증권손상차손</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">194</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">8.외화환산이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">141</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">11.파생상품관련손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">195</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">9.지분법이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">142</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.파생상품평가손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">196</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">10.장기투자증권손상차손환입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">143</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.파생상품거래손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">197</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.매도가능증권손상차손환입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">144</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">다.기타파생상품손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">198</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.만기보유증권손상차손환입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">145</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">12.투자부동산처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">199</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">11.파생상품관련이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">146</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">13.유형자산처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">200</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.파생상품평가이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">147</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.토지처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">201</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.파생상품거래이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">148</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.건물처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">202</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">다.기타파생상품이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">149</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">다.기계장치처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">203</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">12.투자부동산처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">150</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">라.기타유형자산처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">204</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">13.유형자산처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">151</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">14.무형자산처분손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">205</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">가.토지처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">152</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">15.기부금</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">206</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">나.건물처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">153</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">16.사채상환손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">207</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">다.기계장치처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">154</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">17.위약금·보상금·배상금비용</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">208</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL35\">라.기타유형자산처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">155</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">18.기타충당금·준비금전입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">209</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">14.무형자산처분이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">156</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">19.전기오류수정손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">210</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">15.사채상환이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">157</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">20.재해손실</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">211</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">16.법인세환급액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">158</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">21.기타</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">212</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\">");
      out.print(rbox.get("code6400101_amt",Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">17.충당금·준비금환입</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">159</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅷ.법인세비용차감전손익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">217</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\">");
      out.print(rbox.get("code6164_amt",Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">18.전기오류수저이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">160</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅸ.법인세비용</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">218</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\">");
      out.print(rbox.get("code7500101_amt",Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">19.자산수중이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">161</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"t-left font-bold\">Ⅹ.당기순손익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">219</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\">");
      out.print(rbox.get("code616475_amt",Box.THOUSAND_COMMA));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">20.채무면제(조정)이익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">162</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t-left padL25\">21.보험차익</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-center\">163</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right padR5\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
 if(!box.get("excel_yn").equals("Y")) { 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("<textarea name=\"xmlBuf\" style=\"display:none\">");
      out.print(xmlBuf);
      out.write("</textarea>\r\n");
      out.write("</form>\r\n");
 } 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
