/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-02 11:14:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.tax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class adj02003_005f3_005f4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.Box obox = null;
      obox = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("obox", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obox == null){
        obox = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("obox", obox, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
 String xmlBuf = ""; 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- [별지 제3호의3 서식(4)] 이익잉여금처분(결손금처리)계산서 -->\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tajaxSubmitForm(\"xmlUpdate.do\",\"#taxForm\", function(rtn) {\r\n");
      out.write("\t\t\tif(rtn.isOk == \"Y\") {\r\n");
      out.write("\t\t\t\thideServerWorking();\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\talert(rtn.errMsg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form id=\"taxForm\" name=\"taxForm\" method=\"post\" action=\"\" class=\"fType\" style=\"margin:0px\">\r\n");
      out.write("<input type=\"hidden\" name=\"report_id\" \t\tvalue=\"");
      out.print(box.get("report_id"));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"std_yy\" \t\t\tvalue=\"");
      out.print(box.get("std_yy"));
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t<h2 class=\"page-title-2depths\">이익잉여금처분(결손금처리)계산서</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"table-top-control\">\r\n");
      out.write("\t\t<span style=\"float:right;\">[별지 제3호의3 서식(4)]</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"divListData\" class=\"contentsRow\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"table table-bordered order-column table-cover marB0\">\r\n");
      out.write("\t\t\t");
	xmlBuf += "<acc_start_ymd>"+obox.get("acc_start_ymd",Box.DEF_DATE_FMT)+"</acc_start_ymd>\n"
					   +  "<acc_end_ymd>"+obox.get("acc_end_ymd",Box.DEF_DATE_FMT)+"</acc_end_ymd>\n"
					   +  "<corp_nm>"+obox.get("corp_nm")+"</corp_nm>\n"
					   +  "<saupja_no>"+FormatUtil.bizRegiNoFormat(obox.get("saupja_no"))+"</saupja_no>\n"; 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\" bgcolor=\"f6f6f6\">법인명</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">");
      out.print(obox.get("corp_nm"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"15%\" bgcolor=\"f6f6f6\">사업자등록번호</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">");
      out.print(FormatUtil.bizRegiNoFormat(obox.get("saupja_no")));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"f6f6f6\">사업연도</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">");
      out.print(obox.get("acc_start_ymd",Box.DEF_DATE_FMT));
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(obox.get("acc_end_ymd",Box.DEF_DATE_FMT));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"f6f6f6\">처분(처리)확정일</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"8\"></td>\r\n");
      out.write("\t\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"4\" class=\"td-head\" width=\"50%\">1. 이익잉여금처분계산서</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"4\" class=\"td-head\" width=\"50%\">2. 결손금처리계산서</td>\r\n");
      out.write("\t\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"td-head\" width=\"30%\">과목</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"5%\">코드</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"15%\">금액</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"td-head\" width=\"30%\">과목</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"5%\">코드</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-head\" width=\"15%\">금액</td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">I. 미처분이익잉여금<br>(02+03+04-05+06)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">01</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">I. 미처리결손금<br>(31+32+33+34+35)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">30</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 1. 전기이월미처분이익잉여금<br>(또는 전기월 미처리결손금)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">02</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 1. 전기이월미처리결손금<br>(또는 전기이월미처분이익잉여금)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">31</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 2. 회계정책변경의 누적효과</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">03</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 2. 회계정책변경의 누적효과</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">32</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 3. 전기오류수정이익<br>(또는 전기오류수정손실)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">04</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 3. 전기오류수정손실<br>(또는 전기오류수정이익)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">33</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 4. 중간배당액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">05</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 4. 중간배당액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">34</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 5. 당기순이익<br>(또는 당기순손실)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">06</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 5. 당기순손실<br>(또는 당기순이익)</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">35</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">II. 임의적립금 등의 이입액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">08</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">II. 결손금 처리액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">40</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-cetner\">합계</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">10</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 1. 임의적립금이입액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">41</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">III. 이익잉여금 처분액</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">11</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 2. 그 밖의 법정적립금이입액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">42</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 1. 이익준비금 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">12</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 3. 이익준비금이입액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">43</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 2. 기타법정적립금 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">13</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 4. 자본잉여금이입액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">44</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 3. 주식할인발행차금상각액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">14</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">III. 차기이월미처리결손금 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">50</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 4. 배당금 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">15</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">&nbsp;&nbsp;가. 현금배당 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">16</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">&nbsp;&nbsp;나. 주식배당 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">17</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 5. 이익처분에 의한 상여금 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">26</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 6. 사업확장적립금 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">18</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 7. 감채적립금 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">19</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 8. 그 밖의 적립금 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">20</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 9. 「조세특례제한법」상 준비금 등 적립액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">27</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\"> 10. 그 밖의 잉여금처분액 </td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">28</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"t-left\">IV. 차기이월미처분이익잉여금</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-cetner\">25</td>\r\n");
      out.write("\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" style=\"border:none\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("<textarea name=\"xmlBuf\" style=\"display:none\">");
      out.print(xmlBuf);
      out.write("</textarea>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
