/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2019-09-20 00:07:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.tax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;
import egovframework.cbiz.*;
import egovframework.cbiz.util.*;

public final class adj02003_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/com/include/excel_header.jsp", Long.valueOf(1568793281369L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("egovframework.cbiz");
    _jspx_imports_packages.add("egovframework.cbiz.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      egovframework.cbiz.Box box = null;
      box = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("box", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (box == null){
        box = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("box", box, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.cbiz.Box obox = null;
      obox = (egovframework.cbiz.Box) _jspx_page_context.getAttribute("obox", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obox == null){
        obox = new egovframework.cbiz.Box();
        _jspx_page_context.setAttribute("obox", obox, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      egovframework.ubiz.mapper.ent.SesUserEntity uSesEnt = null;
      synchronized (session) {
        uSesEnt = (egovframework.ubiz.mapper.ent.SesUserEntity) _jspx_page_context.getAttribute("uSesEnt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (uSesEnt == null){
          uSesEnt = new egovframework.ubiz.mapper.ent.SesUserEntity();
          _jspx_page_context.setAttribute("uSesEnt", uSesEnt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
 String xmlBuf = ""; 
      out.write('\r');
      out.write('\n');
 if(box.get("excel_yn").equals("Y")) { 
      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
	
	String lm_sAgentType = request.getHeader("User-Agent"); 
	String excel_file_nm = box.get("excel_file_nm");
	excel_file_nm = StringUtil.get8859_1(excel_file_nm); // ìë²ììë ì£¼ìì²ë¦¬
	response.reset();
    if(lm_sAgentType.indexOf("MSIE 5.5") > -1 || lm_sAgentType.indexOf("MSIE 6.0") > -1) {
	    response.setHeader("Content-Type",        "doesn/matter;");
	    response.setHeader("Content-Disposition", "filename="+excel_file_nm+".xls");
    }else {
	    response.setHeader("Content-Type", "application/vnd.ms-excel;charset=UTF-8");
    	response.setHeader("Content-Disposition", "attachment;filename="+excel_file_nm+".xls");
	}
	response.setHeader("Content-Transfer-Encoding", "binary;");
	response.setHeader("Pragma", "no-cache;");
	response.setHeader("Expires", "-1;");

      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\ttd { font-size:12px; font-family:\"ë§ì ê³ ë\", \"Arial\", \"sans-serif\"; color:#00000; text-align:center; border:.5pt solid #000; }\n");
      out.write("</style>\n");
      out.write("<center><h2>");
      out.print(box.get("excel_file_nm"));
      out.write("</h2></center>");
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>[별지 제3호 서식] 법인세 과세표준 및 세액조정계산서</title>\r\n");
      out.write("\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tajaxSubmitForm(\"xmlUpdate.do\",\"#taxForm\", function(rtn) {\r\n");
      out.write("\t\t\tif(rtn.isOk == \"Y\") {\r\n");
      out.write("\t\t\t\thideServerWorking();\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\talert(rtn.errMsg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form id=\"taxForm\" name=\"taxForm\" method=\"post\" action=\"\" class=\"fType\" style=\"margin:0px\">\r\n");
      out.write("<input type=\"hidden\" name=\"report_id\" \tvalue=\"");
      out.print(box.get("report_id"));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"std_yy\" \t\tvalue=\"");
      out.print(box.get("std_yy"));
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<h2 class=\"page-title-2depths\">법인세 과세표준 및 세액조정계산서</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"table-top-control\">\r\n");
      out.write("\t\t<span style=\"float:right;\">[별지 제3호 서식]</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"divListData\" class=\"contentsRow\">\r\n");
      out.write("\t\t<table class=\"table table-bordered order-column\" border=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pad0\" style=\"border:0\" valign=\"top\">\r\n");
      out.write("\t\t\t\t");
	xmlBuf += "<acc_start_ymd>"+StringUtil.getFormatedText(obox.get("acc_start_ymd"),"????-??-??")+"</acc_start_ymd>\n"
						   +  "<acc_end_ymd>"+StringUtil.getFormatedText(obox.get("acc_end_ymd"),"????-??-??")+"</acc_end_ymd>\n"
						   +  "<corp_nm>"+obox.get("corp_nm")+"</corp_nm>\n"
						   +  "<saupja_no>"+FormatUtil.bizRegiNoFormat(obox.get("saupja_no"))+"</saupja_no>\n"; 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered order-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"7\" width=\"5%\" class=\"t-center\">①<br>각<br>사<br>업<br>연<br>도<br>소<br>득<br>금<br>액<br>계<br>산</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" width=\"55%\" class=\"t-left\">(101)결산서상당기순손익</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"5%\" class=\"t-center\">01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"2\" width=\"20%\" class=\"t-center\">소득금액<br>조정</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\" width=\"35%\">(102)익 금 산 입</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">02</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(103)손 금 산 입</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">03</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(104)차가감 소득금액(101+102-103)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">04</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(105)기부금한도초과액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">05</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(106)기부금한도초과 이월금손금산입</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">54</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(107)각 사업연도소득금액(104+105-106)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">06</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered order-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"7\" width=\"5%\" class=\"t-center\">②<br>과<br>세<br>표<br>준<br>계<br>산</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\" width=\"55%\">(108)각 사업연도 소득금액(108=107)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"5%\" class=\"t-center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(109)이월결손금</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">07</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(110)비과세소득</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">08</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(111)소득공제</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">09</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(112)과세표준(108-109-110-111)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"14\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"5\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(159)선박표준이익</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">55</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered order-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"7\" width=\"5%\" class=\"t-center\">③<br>산<br>출<br>세<br>액<br>계<br>산</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\" width=\"55%\">(113)과세표준(112+159)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"5%\" class=\"t-center\">56</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(114)세율</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">11</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"class=\"t-left\">(115)산출세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">12</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(116)지점유보소득(법인세법 제96조)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">13</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(117)세율</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">14</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(118)산출세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">15</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(119)합계(115+118)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">16</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered order-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"13\" width=\"5%\" class=\"t-center\">④<br>납<br>부<br>할<br>세<br>액<br>계<br>산</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" width=\"55%\" class=\"t-left\">(120)산출세액(120=119)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"5%\" class=\"t-center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(121)공제감면세액(ㄱ)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">17</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(122)차감세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">18</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(123)공제감면세액(ㄴ)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(124)가산세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">20</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(125)가감계(122-123+124)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">21</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
 	Box rbox = CodeUtil.getRsBox("PR_ACC_TAX_REPORT","LIST002",box.get("std_yy")+"12","","1110901","","", uSesEnt.dbo); 
								Long pre_tax_amt = rbox.getLong("cur_acum"); // 기납부세액(선급법인세) 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"7\" width=\"5%\" class=\"t-center\">기<br>납<br>부<br>세<br>액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"5\" width=\"5%\" class=\"t-center\">기<br>한<br>내<br>납<br>부<br>세<br>액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-left\" width=\"45%\">(126)중간예납세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">22</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-left\">(127)수시부과세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">23</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
	xmlBuf += "<pre_tax_amt>"+FormatUtil.insertComma(String.valueOf(pre_tax_amt))+"</pre_tax_amt>\n"
									   +  "<pre_tax_amt_min>"+FormatUtil.insertComma(String.valueOf(pre_tax_amt*-1))+"</pre_tax_amt_min>\n"; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-left\">(128)원천납부세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">24</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(FormatUtil.insertComma(String.valueOf(pre_tax_amt)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-left\">(129)간접투자회사 등의 외국납부세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">25</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-left\">(130)소계(126+127+128+129)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">26</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(FormatUtil.insertComma(String.valueOf(pre_tax_amt)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(131)신고납부전가산세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">27</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(132)합계(130+131)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">28</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(FormatUtil.insertComma(String.valueOf(pre_tax_amt)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<td class=\"padR0\" style=\"border:0\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered order-column\" style=\"height:70px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"2\" width=\"5%\" class=\"t-center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" width=\"55%\" class=\"t-left\">(133)감면분추가납부세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"5%\" class=\"t-center\">29</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(134)차감납부할세액(125-132+133)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">30</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(FormatUtil.insertComma(String.valueOf(pre_tax_amt*-1)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered order-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"16\" width=\"5%\" class=\"t-center\">⑤<br>토<br>지<br>등<br><br>양<br>도<br>소<br>득<br>에<br><br>대<br>한<br><br>법<br>인<br>세<br>계<br>산</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"2\" width=\"10%\" class=\"t-center\">양도<br>차익</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" width=\"45%\" class=\"t-left\">(135)등기자산</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"5%\" class=\"t-center\">31</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(136)미등기자산</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">32</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(137)비과세소득</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">33</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(138)과세표준(135+136-137)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">34</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(139)세율</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">35</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(140)산출세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">36</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(141)감면세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">37</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(142)차감세액(140-141)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">38</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(143)공제세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">39</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(144)동업기업 법인세 배분액(가산세 제외)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">58</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(145)가산세액(동업기업 배분액 포함)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">40</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(146)가감계(142-143+144+145)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">41</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"3\" class=\"t-center\">기<br>납<br>부<br>세<br>액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(147)수시부과세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">42</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(148)(&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">43</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(149)계(147+148)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">44</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(150)차감납부할세액(146-149)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">45</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered order-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"6\" width=\"5%\" class=\"t-center\">⑥<br>미<br>환<br>류<br>소<br>득<br>법<br>인<br>세</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" width=\"55%\" class=\"t-left\">(161) 과세대상 미환류소득</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"5%\" class=\"t-center\">59</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(162)세율</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">60</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(163)산출세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">61</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(164)가산세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">62</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(165)이자상당액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">63</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(166)납부할세액(163+164+165)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">64</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"table-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered order-column\">\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"9\" width=\"5%\" class=\"t-center\">⑦<br>세<br>액<br>계</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" width=\"55%\" class=\"t-left\">(151)차감납부할세액계(134+150+166)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"5%\" class=\"t-center\">46</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"t-right\">");
      out.print(FormatUtil.insertComma(String.valueOf(pre_tax_amt*-1)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(152)사실과 다른 회계처리 경정세액공제</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">57</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"t-left\">(153)분납세액계산범위액(151-124-133-145-152+131)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">47</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(FormatUtil.insertComma(String.valueOf(pre_tax_amt*-1)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"3\" width=\"10%\" class=\"t-center\">분납할세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" width=\"45%\" class=\"t-left\">(154)현금납부</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">48</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(155)물납</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">49</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(156)계(154+155)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">50</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"3\" class=\"t-center\">차감납부세액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(157)현금납부</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">51</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(FormatUtil.insertComma(String.valueOf(pre_tax_amt*-1)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(158)물납</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">52</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=\"28\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"t-left\">(160)계(157+158)<br>(160=(151-152-156))</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-center\">53</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"t-right\">");
      out.print(FormatUtil.insertComma(String.valueOf(pre_tax_amt*-1)));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("<textarea name=\"xmlBuf\" style=\"display:none\">");
      out.print(xmlBuf);
      out.write("</textarea>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
